package pbo.Level3;

import javax.swing.JOptionPane;

public class Coding_quiz extends javax.swing.JFrame {
    public int fl_sudah_program_selesai = 0;
    /**
     * Creates new form Coding_quiz
     */
    public Coding_quiz() {
        initComponents();
    }
//jawaban : float hasil_generate = Math.pow(a, 2)/3f
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jawaban_nya_3 = new javax.swing.JTextField();
        jawaban_nya_x = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kodereturn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Coding Quiz");
        setMinimumSize(new java.awt.Dimension(600, 235));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("//contoh : 2 = 1.3333333333333, 4 = 5.333333333333333");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 530, 20);

        jLabel2.setText("public float generate_code(int x){");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 30, 190, 20);

        jLabel4.setText("//skrip akan menghasilkan kode dengan melakukan perhitungan dari parameter yang dipasingkan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 50, 530, 20);
        getContentPane().add(jawaban_nya_3);
        jawaban_nya_3.setBounds(260, 90, 30, 22);
        getContentPane().add(jawaban_nya_x);
        jawaban_nya_x.setBounds(200, 90, 30, 22);

        jLabel3.setText("float hasil_generate = Math.pow(              , 2)/             f");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 450, 20);
        getContentPane().add(kodereturn);
        kodereturn.setBounds(20, 110, 150, 30);

        jLabel5.setText("...");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 37, 16);

        jLabel6.setText("...");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 140, 37, 16);

        jButton1.setText("Cek");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 170, 560, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jawaban_nya_3.getText().equals("3") && jawaban_nya_x.getText().equals("x") && kodereturn.getText().equals("return hasil_generate;")){ 
            fl_sudah_program_selesai = 1;
            this.setVisible(false);
            JOptionPane.showMessageDialog(this, "Mantap ", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Kode masih salah!", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coding_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coding_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coding_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coding_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coding_quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jawaban_nya_3;
    private javax.swing.JTextField jawaban_nya_x;
    private javax.swing.JTextField kodereturn;
    // End of variables declaration//GEN-END:variables
}
