package pbo.Level1;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Game extends javax.swing.JFrame {

    private Creature[] mob = new Creature[]{new Warrior(), new Archer(), new Mage(), new Priest(), new Goblin()};
    private boolean click = false, win = false;
    private ArrayList tmp = new ArrayList();
    private Creature[][] papan = new Creature[7][7];
    private int c = 0;
    private String soal;
    private long comb;
    
    public boolean getWin(){
        return win;
    }
    
    private void Hover(javax.swing.JPanel p, boolean b){
        if (b) {
            tmp.add(p);
            p.setBackground(Color.BLUE);
        }else {
            tmp.clear();
            p.setBackground(Color.WHITE);
        }
        click = b;
    }
    
    public boolean cek(){
        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 7; j++) {
                if (papan[i][j] != null) {
                    if (papan[i][j] instanceof Goblin) {
                        return false;
                    }
                }
            }
        }
        return true;
    }
    
    private void change(javax.swing.JLabel troop, int x, int y){
        troop.setLocation(x*100+10, y*100);
        troop.setVisible(true);
        papan[y][x].Attack(papan, x, y);
        ((javax.swing.JPanel) tmp.get(0)).setVisible(false);
        Hover(((javax.swing.JPanel) tmp.remove(0)), false);
        c++;
        if (cek()) {
            win = true;
            JOptionPane.showMessageDialog(this, (soal + ", Kombinasi ke-" + comb), "Quetion", JOptionPane.QUESTION_MESSAGE);
            this.setVisible(false);
        }else{
            if (c == 4) {
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, ("You Lose.."));
            }
        }
    }
    
    private void put(int y, int x){
        if (click) {
            javax.swing.JPanel curr = ((javax.swing.JPanel) tmp.get(0));
            if (curr == jPanel50) {
                if (papan[y][x] == null) {
                    papan[y][x] = mob[0];
                    change(Warrior_copy, x, y);
                }
            }else if (curr == jPanel51) {
                if (papan[y][x] == null) {
                    papan[y][x] = mob[1];
                    change(Archer_copy, x, y);
                }
            }else if (curr == jPanel52) {
                if (papan[y][x] == null) {
                    papan[y][x] = mob[2];
                    change(Mage_copy, x, y);
                }
            }else if (curr == jPanel53) {
                if (papan[y][x] instanceof Warrior) {
                    papan[y][x] = mob[3];
                    ((Priest)papan[y][x]).Heal(jPanel50, Warrior_copy, Priest_copy, x, y, curr, tmp);
                    click = false;
                }else if (papan[y][x] instanceof Archer) {
                    papan[y][x] = mob[3];
                    ((Priest)papan[y][x]).Heal(jPanel51, Archer_copy, Priest_copy, x, y, curr, tmp);
                    click = false;
                }else if (papan[y][x] instanceof Mage) {
                    papan[y][x] = mob[3];
                    ((Priest)papan[y][x]).Heal(jPanel52, Mage_copy, Priest_copy, x, y, curr, tmp);
                    click = false;
                }
            }
        }
    }
    
    private void add_papan(int y, int x, javax.swing.JLabel goblin){
        papan[y][x] = new Goblin(goblin);
    }
    
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }
    
    public Game(String soal, long comb) {
        initComponents();
        this.soal = soal;
        this.comb = comb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Petunjuk = new javax.swing.JFrame();
        petunjuk = new javax.swing.JLabel();
        Warrior_copy = new javax.swing.JLabel();
        Warrior_copy.setVisible(false);
        Archer_copy = new javax.swing.JLabel();
        Mage_copy = new javax.swing.JLabel();
        Priest_copy = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel00 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Lubang1 = new javax.swing.JLabel();
        jLabel01 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Lubang2 = new javax.swing.JLabel();
        jLabel02 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel03 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Goblin13 = new javax.swing.JLabel();
        jLabel04 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel05 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Goblin21 = new javax.swing.JLabel();
        jLabel06 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Goblin3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Lubang3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Goblin14 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        Lubang8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        Goblin22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        Goblin1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        Goblin4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        Goblin8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        Goblin11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        Goblin19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        Goblin23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        Goblin2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        Goblin5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        Goblin16 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        Lubang9 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        Goblin24 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        Lubang4 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        Goblin6 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        Goblin9 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        Goblin12 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        Lubang10 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        Lubang5 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        Lubang6 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        Goblin10 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        Goblin17 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        Lubang11 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        Goblin7 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        Lubang7 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        Goblin18 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        Goblin20 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        Goblin25 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        Warrior = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        Archer = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        Mage = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        Priest = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();

        Petunjuk.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Petunjuk.setTitle("Petunjuk");
        Petunjuk.setLocation(new java.awt.Point(240, 100));
        Petunjuk.setMinimumSize(new java.awt.Dimension(1014, 672));
        Petunjuk.setResizable(false);
        Petunjuk.getContentPane().setLayout(null);

        petunjuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Petunjuk.png"))); // NOI18N
        petunjuk.setPreferredSize(new java.awt.Dimension(1000, 634));
        Petunjuk.getContentPane().add(petunjuk);
        petunjuk.setBounds(0, 0, 1000, 634);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Game");
        setLocation(new java.awt.Point(300, 50));
        setMinimumSize(new java.awt.Dimension(910, 738));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        Warrior_copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Warrior_copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_warrior.png"))); // NOI18N
        Warrior_copy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Warrior_copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Warrior_copyMouseClicked(evt);
            }
        });
        getContentPane().add(Warrior_copy);
        Warrior_copy.setBounds(940, 0, 80, 98);

        Archer_copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_archer.png"))); // NOI18N
        Archer_copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Archer_copyMouseClicked(evt);
            }
        });
        getContentPane().add(Archer_copy);
        Archer_copy.setBounds(940, 0, 80, 98);

        Mage_copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_mage.png"))); // NOI18N
        Mage_copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mage_copyMouseClicked(evt);
            }
        });
        getContentPane().add(Mage_copy);
        Mage_copy.setBounds(940, 0, 80, 98);

        Priest_copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_priest.png"))); // NOI18N
        getContentPane().add(Priest_copy);
        Priest_copy.setBounds(940, 0, 80, 98);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel00MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel00);
        jLabel00.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        Lubang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel2.add(Lubang1);
        Lubang1.setBounds(1, 1, 98, 98);

        jLabel01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel2.add(jLabel01);
        jLabel01.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(100, 0, 100, 100);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        Lubang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel3.add(Lubang2);
        Lubang2.setBounds(1, 1, 98, 98);

        jLabel02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel3.add(jLabel02);
        jLabel02.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(200, 0, 100, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel03MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel03);
        jLabel03.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 0, 100, 100);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        Goblin13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel5.add(Goblin13);
        Goblin13.setBounds(9, 1, 80, 98);
        add_papan(0,4,Goblin13);

        jLabel04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel04MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel04);
        jLabel04.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(400, 0, 100, 100);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jLabel05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel05MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel05);
        jLabel05.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(500, 0, 100, 100);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        Goblin21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel7.add(Goblin21);
        Goblin21.setBounds(9, 1, 80, 98);
        add_papan(0,6,Goblin21);

        jLabel06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel06MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel06);
        jLabel06.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(600, 0, 100, 100);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel10);
        jLabel10.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 100, 100, 100);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(null);

        Goblin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Goblin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel9.add(Goblin3);
        Goblin3.setBounds(9, 1, 80, 98);
        add_papan(1,1,Goblin3);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked1(evt);
            }
        });
        jPanel9.add(jLabel11);
        jLabel11.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(100, 100, 100, 100);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(null);

        Lubang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel10.add(Lubang3);
        Lubang3.setBounds(1, 1, 98, 98);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel10.add(jLabel12);
        jLabel12.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(200, 100, 100, 100);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(null);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel13);
        jLabel13.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel11);
        jPanel11.setBounds(300, 100, 100, 100);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(null);

        Goblin14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel12.add(Goblin14);
        Goblin14.setBounds(9, 1, 80, 98);
        add_papan(1,4,Goblin14);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel14);
        jLabel14.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel12);
        jPanel12.setBounds(400, 100, 100, 100);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(null);

        Lubang8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel13.add(Lubang8);
        Lubang8.setBounds(1, 1, 98, 98);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel13.add(jLabel15);
        jLabel15.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel13);
        jPanel13.setBounds(500, 100, 100, 100);

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(null);

        Goblin22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel14.add(Goblin22);
        Goblin22.setBounds(9, 1, 80, 98);
        add_papan(1,6,Goblin22);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel16);
        jLabel16.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel14);
        jPanel14.setBounds(600, 100, 100, 100);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(null);

        Goblin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel15.add(Goblin1);
        Goblin1.setBounds(9, 1, 80, 98);
        add_papan(2,0,Goblin1);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel20);
        jLabel20.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel15);
        jPanel15.setBounds(0, 200, 100, 100);

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(null);

        Goblin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Goblin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel16.add(Goblin4);
        Goblin4.setBounds(9, 1, 80, 98);
        add_papan(2,1,Goblin4);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel16.add(jLabel21);
        jLabel21.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel16);
        jPanel16.setBounds(100, 200, 100, 100);

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(null);

        Goblin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel17.add(Goblin8);
        Goblin8.setBounds(9, 1, 80, 98);
        add_papan(2,2,Goblin8);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel17.add(jLabel22);
        jLabel22.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel17);
        jPanel17.setBounds(200, 200, 100, 100);

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(null);

        Goblin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel18.add(Goblin11);
        Goblin11.setBounds(9, 1, 80, 98);
        add_papan(2,3,Goblin11);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel18.add(jLabel23);
        jLabel23.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel18);
        jPanel18.setBounds(300, 200, 100, 100);

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(null);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel19.add(jLabel24);
        jLabel24.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel19);
        jPanel19.setBounds(400, 200, 100, 100);

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(null);

        Goblin19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel20.add(Goblin19);
        Goblin19.setBounds(9, 1, 80, 98);
        add_papan(2,5,Goblin19);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel20.add(jLabel25);
        jLabel25.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel20);
        jPanel20.setBounds(500, 200, 100, 100);

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setLayout(null);

        Goblin23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel21.add(Goblin23);
        Goblin23.setBounds(9, 1, 80, 98);
        add_papan(2,6,Goblin23);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel26);
        jLabel26.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel21);
        jPanel21.setBounds(600, 200, 100, 100);

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setLayout(null);

        Goblin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel22.add(Goblin2);
        Goblin2.setBounds(9, 1, 80, 98);
        add_papan(3,0,Goblin2);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel22.add(jLabel30);
        jLabel30.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel22);
        jPanel22.setBounds(0, 300, 100, 100);

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel23.setLayout(null);

        Goblin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Goblin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel23.add(Goblin5);
        Goblin5.setBounds(9, 1, 80, 98);
        add_papan(3,1,Goblin5);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel23.add(jLabel31);
        jLabel31.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel23);
        jPanel23.setBounds(100, 300, 100, 100);

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setLayout(null);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel24.add(jLabel32);
        jLabel32.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel24);
        jPanel24.setBounds(200, 300, 100, 100);

        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel25.setLayout(null);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel25.add(jLabel33);
        jLabel33.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel25);
        jPanel25.setBounds(300, 300, 100, 100);

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel26.setLayout(null);

        Goblin16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel26.add(Goblin16);
        Goblin16.setBounds(9, 1, 80, 98);
        add_papan(3,4,Goblin16);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel26.add(jLabel34);
        jLabel34.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel26);
        jPanel26.setBounds(400, 300, 100, 100);

        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel27.setLayout(null);

        Lubang9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel27.add(Lubang9);
        Lubang9.setBounds(1, 1, 98, 98);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel27.add(jLabel35);
        jLabel35.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel27);
        jPanel27.setBounds(500, 300, 100, 100);

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel28.setLayout(null);

        Goblin24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel28.add(Goblin24);
        Goblin24.setBounds(9, 1, 80, 98);
        add_papan(3,6,Goblin24);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel28.add(jLabel36);
        jLabel36.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel28);
        jPanel28.setBounds(600, 300, 100, 100);

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel29.setLayout(null);

        Lubang4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel29.add(Lubang4);
        Lubang4.setBounds(1, 1, 98, 98);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel29.add(jLabel40);
        jLabel40.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel29);
        jPanel29.setBounds(0, 400, 100, 100);

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.setLayout(null);

        Goblin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Goblin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel30.add(Goblin6);
        Goblin6.setBounds(9, 1, 80, 98);
        add_papan(4,1,Goblin6);

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel30.add(jLabel41);
        jLabel41.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel30);
        jPanel30.setBounds(100, 400, 100, 100);

        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel31.setLayout(null);

        Goblin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel31.add(Goblin9);
        Goblin9.setBounds(9, 1, 80, 98);
        add_papan(4,2,Goblin9);

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        jPanel31.add(jLabel42);
        jLabel42.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel31);
        jPanel31.setBounds(200, 400, 100, 100);

        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel32.setLayout(null);

        Goblin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel32.add(Goblin12);
        Goblin12.setBounds(9, 1, 80, 98);
        add_papan(4,3,Goblin12);

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        jPanel32.add(jLabel43);
        jLabel43.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel32);
        jPanel32.setBounds(300, 400, 100, 100);

        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel33.setLayout(null);

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel33.add(jLabel44);
        jLabel44.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel33);
        jPanel33.setBounds(400, 400, 100, 100);

        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel34.setLayout(null);

        Lubang10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel34.add(Lubang10);
        Lubang10.setBounds(1, 1, 98, 98);

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel34.add(jLabel45);
        jLabel45.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel34);
        jPanel34.setBounds(500, 400, 100, 100);

        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel35.setLayout(null);

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel35.add(jLabel46);
        jLabel46.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel35);
        jPanel35.setBounds(600, 400, 100, 100);

        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel36.setLayout(null);

        Lubang5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel36.add(Lubang5);
        Lubang5.setBounds(1, 1, 98, 98);

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel36.add(jLabel50);
        jLabel50.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel36);
        jPanel36.setBounds(0, 500, 100, 100);

        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel37.setLayout(null);

        Lubang6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel37.add(Lubang6);
        Lubang6.setBounds(1, 1, 98, 98);

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel37.add(jLabel51);
        jLabel51.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel37);
        jPanel37.setBounds(100, 500, 100, 100);

        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel38.setLayout(null);

        Goblin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel38.add(Goblin10);
        Goblin10.setBounds(9, 1, 80, 98);
        add_papan(5,2,Goblin10);

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        jPanel38.add(jLabel52);
        jLabel52.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel38);
        jPanel38.setBounds(200, 500, 100, 100);

        jPanel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel39.setLayout(null);

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
        });
        jPanel39.add(jLabel53);
        jLabel53.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel39);
        jPanel39.setBounds(300, 500, 100, 100);

        jPanel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel40.setLayout(null);

        Goblin17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel40.add(Goblin17);
        Goblin17.setBounds(9, 1, 80, 98);
        add_papan(5,4,Goblin17);

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel40.add(jLabel54);
        jLabel54.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel40);
        jPanel40.setBounds(400, 500, 100, 100);

        jPanel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel41.setLayout(null);

        Lubang11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel41.add(Lubang11);
        Lubang11.setBounds(1, 1, 98, 98);

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel41.add(jLabel55);
        jLabel55.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel41);
        jPanel41.setBounds(500, 500, 100, 100);

        jPanel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel42.setLayout(null);

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        jPanel42.add(jLabel56);
        jLabel56.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel42);
        jPanel42.setBounds(600, 500, 100, 100);

        jPanel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel43.setLayout(null);

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jPanel43.add(jLabel60);
        jLabel60.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel43);
        jPanel43.setBounds(0, 600, 100, 100);

        jPanel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel44.setLayout(null);

        Goblin7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Goblin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel44.add(Goblin7);
        Goblin7.setBounds(9, 1, 80, 98);
        add_papan(6,1,Goblin7);

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel44.add(jLabel61);
        jLabel61.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel44);
        jPanel44.setBounds(100, 600, 100, 100);

        jPanel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel45.setLayout(null);

        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel45.add(jLabel62);
        jLabel62.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel45);
        jPanel45.setBounds(200, 600, 100, 100);

        jPanel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel46.setLayout(null);

        Lubang7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/lubang.png"))); // NOI18N
        jPanel46.add(Lubang7);
        Lubang7.setBounds(1, 1, 98, 98);

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jPanel46.add(jLabel63);
        jLabel63.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel46);
        jPanel46.setBounds(300, 600, 100, 100);

        jPanel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel47.setLayout(null);

        Goblin18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel47.add(Goblin18);
        Goblin18.setBounds(9, 1, 80, 98);
        add_papan(6,4,Goblin18);

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel47.add(jLabel64);
        jLabel64.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel47);
        jPanel47.setBounds(400, 600, 100, 100);

        jPanel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel48.setLayout(null);

        Goblin20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel48.add(Goblin20);
        Goblin20.setBounds(9, 1, 80, 98);
        add_papan(6,5,Goblin20);

        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });
        jPanel48.add(jLabel65);
        jLabel65.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel48);
        jPanel48.setBounds(500, 600, 100, 100);

        jPanel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel49.setLayout(null);

        Goblin25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_goblin.png"))); // NOI18N
        jPanel49.add(Goblin25);
        Goblin25.setBounds(9, 1, 80, 98);
        add_papan(6,6,Goblin25);

        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/Background rumput.jpg"))); // NOI18N
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        jPanel49.add(jLabel66);
        jLabel66.setBounds(1, 1, 98, 98);

        getContentPane().add(jPanel49);
        jPanel49.setBounds(600, 600, 100, 100);

        jPanel50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel50.setLayout(null);

        Warrior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Warrior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_warrior.png"))); // NOI18N
        Warrior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WarriorMouseClicked(evt);
            }
        });
        jPanel50.add(Warrior);
        Warrior.setBounds(10, 1, 80, 98);

        getContentPane().add(jPanel50);
        jPanel50.setBounds(750, 175, 100, 100);

        jPanel51.setBackground(new java.awt.Color(255, 255, 255));
        jPanel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel51.setLayout(null);

        Archer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Archer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_archer.png"))); // NOI18N
        Archer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArcherMouseClicked(evt);
            }
        });
        jPanel51.add(Archer);
        Archer.setBounds(10, 1, 80, 98);

        getContentPane().add(jPanel51);
        jPanel51.setBounds(750, 300, 100, 100);

        jPanel52.setBackground(new java.awt.Color(255, 255, 255));
        jPanel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.setLayout(null);

        Mage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_mage.png"))); // NOI18N
        Mage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MageMouseClicked(evt);
            }
        });
        jPanel52.add(Mage);
        Mage.setBounds(10, 1, 80, 98);

        getContentPane().add(jPanel52);
        jPanel52.setBounds(750, 425, 100, 100);

        jPanel53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel53.setLayout(null);

        Priest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Priest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/game_priest.png"))); // NOI18N
        Priest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PriestMouseClicked(evt);
            }
        });
        jPanel53.add(Priest);
        Priest.setBounds(10, 1, 80, 98);

        getContentPane().add(jPanel53);
        jPanel53.setBounds(750, 550, 100, 100);

        Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level1/image/info.png"))); // NOI18N
        Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoMouseClicked(evt);
            }
        });
        getContentPane().add(Info);
        Info.setBounds(762, 50, 75, 75);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoMouseClicked
        Petunjuk.setVisible(true);
    }//GEN-LAST:event_InfoMouseClicked

    private void WarriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WarriorMouseClicked
        if (tmp.size() > 0) {
            if (tmp.get(0) == jPanel50) Hover(jPanel50, false);
            else{
                if (click) Hover((javax.swing.JPanel)tmp.remove(0), false);
                Hover(jPanel50, true);
            }
        }else Hover(jPanel50, true);
    }//GEN-LAST:event_WarriorMouseClicked

    private void ArcherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArcherMouseClicked
        if (tmp.size() > 0) {
            if (tmp.get(0) == jPanel51) Hover(jPanel51, false);
            else{
                if (click) Hover((javax.swing.JPanel)tmp.remove(0), false);
                Hover(jPanel51, true);
            }
        }else Hover(jPanel51, true);
    }//GEN-LAST:event_ArcherMouseClicked

    private void MageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MageMouseClicked
        if (tmp.size() > 0) {
            if (tmp.get(0) == jPanel52) Hover(jPanel52, false);
            else{
                if (click) Hover((javax.swing.JPanel)tmp.remove(0), false);
                Hover(jPanel52, true);
            }
        }else Hover(jPanel52, true);
    }//GEN-LAST:event_MageMouseClicked

    private void PriestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PriestMouseClicked
        if (tmp.size() > 0) {
            if (tmp.get(0) == jPanel53) Hover(jPanel53, false);
            else{
                if (click) Hover((javax.swing.JPanel)tmp.remove(0), false);
                Hover(jPanel53, true);
            }
        }else Hover(jPanel53, true);
    }//GEN-LAST:event_PriestMouseClicked

    private void jLabel00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel00MouseClicked
        put(0,0);
    }//GEN-LAST:event_jLabel00MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        put(1,0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        put(6,0);
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel03MouseClicked
        put(0,3);
    }//GEN-LAST:event_jLabel03MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        put(1,3);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        put(3,2);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        put(3,3);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked
        put(5,3);
    }//GEN-LAST:event_jLabel53MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        put(6,2);
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        put(4,4);
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel05MouseClicked
        put(0,5);
    }//GEN-LAST:event_jLabel05MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        put(4,6);
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        put(5,6);
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        put(2,0);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel11MouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked1
        put(1,1);
    }//GEN-LAST:event_jLabel11MouseClicked1

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        put(3,0);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        put(2,1);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        put(3,1);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        put(4,1);
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        put(6,1);
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        put(2,2);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        put(4,2);
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        put(5,2);
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        put(2,3);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        put(4,3);
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel04MouseClicked
        put(0,4);
    }//GEN-LAST:event_jLabel04MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        put(1,4);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        put(2,4);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        put(3,4);
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        put(5,4);
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        put(6,4);
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        put(2,5);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
        put(6,5);
    }//GEN-LAST:event_jLabel65MouseClicked

    private void jLabel06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel06MouseClicked
        put(0,6);
    }//GEN-LAST:event_jLabel06MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        put(1,6);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        put(2,6);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        put(3,6);
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
        put(6,6);
    }//GEN-LAST:event_jLabel66MouseClicked

    private void Warrior_copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Warrior_copyMouseClicked
        if (tmp.size() > 0) {
            if ((javax.swing.JPanel) tmp.get(0) == jPanel53) {
                java.awt.Point coord = Warrior_copy.getLocation();
                int x = (((int)coord.getX())-10)/100;
                int y = ((int)coord.getY())/100;
                put(y,x);
            }
        }
    }//GEN-LAST:event_Warrior_copyMouseClicked

    private void Archer_copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Archer_copyMouseClicked
        if (tmp.size() > 0) {
            if ((javax.swing.JPanel) tmp.get(0) == jPanel53) {
                java.awt.Point coord = Archer_copy.getLocation();
                int x = (((int)coord.getX())-10)/100;
                int y = ((int)coord.getY())/100;
                put(y,x);
            }
        }
    }//GEN-LAST:event_Archer_copyMouseClicked

    private void Mage_copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mage_copyMouseClicked
        if (tmp.size() > 0) {
            if ((javax.swing.JPanel) tmp.get(0) == jPanel53) {
                java.awt.Point coord = Mage_copy.getLocation();
                int x = (((int)coord.getX())-10)/100;
                int y = ((int)coord.getY())/100;
                put(y,x);
            }
        }
    }//GEN-LAST:event_Mage_copyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Archer;
    private javax.swing.JLabel Archer_copy;
    private javax.swing.JLabel Goblin1;
    private javax.swing.JLabel Goblin10;
    private javax.swing.JLabel Goblin11;
    private javax.swing.JLabel Goblin12;
    private javax.swing.JLabel Goblin13;
    private javax.swing.JLabel Goblin14;
    private javax.swing.JLabel Goblin16;
    private javax.swing.JLabel Goblin17;
    private javax.swing.JLabel Goblin18;
    private javax.swing.JLabel Goblin19;
    private javax.swing.JLabel Goblin2;
    private javax.swing.JLabel Goblin20;
    private javax.swing.JLabel Goblin21;
    private javax.swing.JLabel Goblin22;
    private javax.swing.JLabel Goblin23;
    private javax.swing.JLabel Goblin24;
    private javax.swing.JLabel Goblin25;
    private javax.swing.JLabel Goblin3;
    private javax.swing.JLabel Goblin4;
    private javax.swing.JLabel Goblin5;
    private javax.swing.JLabel Goblin6;
    private javax.swing.JLabel Goblin7;
    private javax.swing.JLabel Goblin8;
    private javax.swing.JLabel Goblin9;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel Lubang1;
    private javax.swing.JLabel Lubang10;
    private javax.swing.JLabel Lubang11;
    private javax.swing.JLabel Lubang2;
    private javax.swing.JLabel Lubang3;
    private javax.swing.JLabel Lubang4;
    private javax.swing.JLabel Lubang5;
    private javax.swing.JLabel Lubang6;
    private javax.swing.JLabel Lubang7;
    private javax.swing.JLabel Lubang8;
    private javax.swing.JLabel Lubang9;
    private javax.swing.JLabel Mage;
    private javax.swing.JLabel Mage_copy;
    private javax.swing.JFrame Petunjuk;
    private javax.swing.JLabel Priest;
    private javax.swing.JLabel Priest_copy;
    private javax.swing.JLabel Warrior;
    private javax.swing.JLabel Warrior_copy;
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel01;
    private javax.swing.JLabel jLabel02;
    private javax.swing.JLabel jLabel03;
    private javax.swing.JLabel jLabel04;
    private javax.swing.JLabel jLabel05;
    private javax.swing.JLabel jLabel06;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel petunjuk;
    // End of variables declaration//GEN-END:variables
}
