package pbo.projek;

import java.util.ArrayList;
import java.sql.*;

public class Highscore extends javax.swing.JFrame {
    private String username;
    private int waktu;
    private int level_ke;
    private ArrayList<String> listleaderboard = new ArrayList<>();
    private ArrayList<Integer> listleaderboardscore = new ArrayList<>();
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/escaperoom";
    static final String USER = "root";
    static final String PASS = "";
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    private String kalimat;
    
    /**
     * Creates new form Highscore
     */
    public Highscore() {
        initComponents();
    }
    
    public Highscore(int level_ke, String username, int waktu){
        initComponents();
        this.level_ke = level_ke;
        this.username = username;
        this.waktu = waktu;
        this.kalimat = " dapat menyelesaikan level " + level_ke + " dalam ";
        eksekusi();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        list1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Leaderboard");
        setLocation(new java.awt.Point(450, 260));
        setMaximumSize(new java.awt.Dimension(611, 350));
        setMinimumSize(new java.awt.Dimension(611, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LEADERBOARD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 270, 50);

        list1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        getContentPane().add(list1);
        list1.setBounds(20, 70, 560, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void Database(int lvl, String s){
        String[] level = new String[]{"level1","level2","level3","level4"};
        listleaderboard.clear();
        listleaderboardscore.clear();
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            if (s.equalsIgnoreCase("load")) {
                String sql = "SELECT * FROM " + level[lvl-1] + " ORDER BY score ASC";
                rs = stmt.executeQuery(sql);
                while(rs.next()){
                    listleaderboard.add(rs.getString("username"));
                    listleaderboardscore.add(rs.getInt("score"));
                }
            }else if (s.equalsIgnoreCase("update")){
                String sql = "UPDATE " + level[lvl-1] + " SET score = "+ waktu +" WHERE username = '"+ username +"'";
                stmt.executeUpdate(sql);
            }
            stmt.close();
            conn.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void eksekusi(){
        if(!username.equalsIgnoreCase("4d-M1n")){
            Database(level_ke, "update");
        }
        Database(level_ke, "load");
        for(int i = 0; i < listleaderboard.size(); i++){
            if (listleaderboardscore.get(i) == Integer.MAX_VALUE) {
                list1.add(listleaderboard.get(i)+ " belum menyelesaikan level " + level_ke);
            }else{
                int m = listleaderboardscore.get(i)/60, s = listleaderboardscore.get(i)%60;
                list1.add(listleaderboard.get(i)+ kalimat + (m > 0 ? (m + " menit " + s + " detik") : (s + " detik")));
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Highscore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
