package pbo.Level2;

import pbo.projek.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DecimalFormat;
import javax.swing.Timer;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

public class Level2 extends javax.swing.JFrame implements Methods {

/**
 *
 * @author Yoanes Leonardi - 221116999
 */
    
    private Select_Level sl = new Select_Level();
    private Setting setting;
    private String username;
    
    //TIMER
    private Timer timer;
    int second, minute;
    private String ddSecond, ddMinute;
    private DecimalFormat dFormat = new DecimalFormat("00");

    //INVENTORY
    private Inventory i = new Inventory(username);
    private boolean click = false, Chestkey = false, Safekey = false, Arloji = false, Isichestkecil = false;
    private Map<javax.swing.JLabel, Boolean> have = new HashMap<>();
    private int[] coord_y = new int[]{140, 270, 405, 535};
    private ArrayList tmp = new ArrayList();

    //hint
    private boolean hsafekey = false, hchestkey = false, harloji = false, hisichest = false;
    private boolean available_hint = true;
    
    //music
    private Clip clip;
    private Clip main;

    /**
     * Creates new form Level2
     */
    public Level2() {
        initComponents();
        Playmusic("Music\\Level2.wav");
    }
    
    public Level2(String username, Select_Level sl, Clip main, Setting setting) {
        initComponents();
        this.sl = sl;
        this.main = main;
        this.setting = setting;
        this.username = username;
        if (setting.isPlaying_music()) {
            Playmusic("Music\\Level2.wav");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Passcodepintu = new javax.swing.JFrame();
        passcode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        isichest = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        hintchestkey = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hintisichest = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hintsafekey = new javax.swing.JFrame();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        belakangfigura = new javax.swing.JFrame();
        safekey = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hintarloji = new javax.swing.JFrame();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        isiarloji = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        papan_penunjuk_1 = new javax.swing.JLabel();
        hint_3 = new javax.swing.JLabel();
        hint_2 = new javax.swing.JLabel();
        hint_2.setVisible(false);
        hint_1 = new javax.swing.JLabel();
        hint_1.setVisible(false);
        hint_0 = new javax.swing.JLabel();
        hint_0.setVisible(false);
        Pintu = new javax.swing.JLabel();
        arloji = new javax.swing.JLabel();
        isichestkecil = new javax.swing.JLabel();
        chestopen = new javax.swing.JLabel();
        chestclose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passcodedoor = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        safeopen = new javax.swing.JLabel();
        safeclose = new javax.swing.JLabel();
        figura = new javax.swing.JLabel();
        chestkey = new javax.swing.JLabel();
        Inventory_click1 = new javax.swing.JLabel();
        Inventory_click1.setVisible(false);
        Inventory_click2 = new javax.swing.JLabel();
        Inventory_click2.setVisible(false);
        Inventory_click3 = new javax.swing.JLabel();
        Inventory_click3.setVisible(false);
        Inventory_click4 = new javax.swing.JLabel();
        Inventory_click4.setVisible(false);
        i_chestkey = new javax.swing.JLabel();
        i_isichestkecil = new javax.swing.JLabel();
        i_arloji = new javax.swing.JLabel();
        i_safekey = new javax.swing.JLabel();
        Invetory_box1 = new javax.swing.JLabel();
        Invetory_box2 = new javax.swing.JLabel();
        Invetory_box3 = new javax.swing.JLabel();
        Invetory_box4 = new javax.swing.JLabel();
        Inventory_backgound = new javax.swing.JLabel();
        latar = new javax.swing.JLabel();

        Passcodepintu.setLocation(new java.awt.Point(500, 250));
        Passcodepintu.setLocationByPlatform(true);
        Passcodepintu.setMinimumSize(new java.awt.Dimension(336, 480));
        Passcodepintu.setUndecorated(true);
        Passcodepintu.setResizable(false);
        Passcodepintu.setSize(new java.awt.Dimension(336, 480));

        passcode.setEditable(false);
        passcode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passcode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("4");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("7");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("0");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("3");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("6");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("<--");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText("8");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("ENTER");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER THE CORRECT 4 DIGIT CODE");

        javax.swing.GroupLayout PasscodepintuLayout = new javax.swing.GroupLayout(Passcodepintu.getContentPane());
        Passcodepintu.getContentPane().setLayout(PasscodepintuLayout);
        PasscodepintuLayout.setHorizontalGroup(
            PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasscodepintuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PasscodepintuLayout.createSequentialGroup()
                        .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PasscodepintuLayout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasscodepintuLayout.createSequentialGroup()
                                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasscodepintuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PasscodepintuLayout.createSequentialGroup()
                                .addComponent(passcode, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PasscodepintuLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(100, 100, 100))
        );
        PasscodepintuLayout.setVerticalGroup(
            PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasscodepintuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passcode, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PasscodepintuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        isichest.setLocationByPlatform(true);
        isichest.setMinimumSize(new java.awt.Dimension(457, 599));
        isichest.setUndecorated(true);
        isichest.setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/isichest.png"))); // NOI18N

        javax.swing.GroupLayout isichestLayout = new javax.swing.GroupLayout(isichest.getContentPane());
        isichest.getContentPane().setLayout(isichestLayout);
        isichestLayout.setHorizontalGroup(
            isichestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isichestLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        isichestLayout.setVerticalGroup(
            isichestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isichestLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        hintchestkey.setLocation(new java.awt.Point(410, 322));
        hintchestkey.setLocationByPlatform(true);
        hintchestkey.setMinimumSize(new java.awt.Dimension(355, 322));
        hintchestkey.setUndecorated(true);
        hintchestkey.setResizable(false);
        hintchestkey.setSize(new java.awt.Dimension(355, 322));
        hintchestkey.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("the ceiling lamp");
        hintchestkey.getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 130, 250, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("There is a chestkey around");
        hintchestkey.getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 80, 250, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/hintcard.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(345, 280));
        hintchestkey.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 345, 280);

        hintisichest.setLocation(new java.awt.Point(410, 322));
        hintisichest.setLocationByPlatform(true);
        hintisichest.setMinimumSize(new java.awt.Dimension(355, 322));
        hintisichest.setUndecorated(true);
        hintisichest.setResizable(false);
        hintisichest.setSize(new java.awt.Dimension(355, 322));
        hintisichest.getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("the letters");
        hintisichest.getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 160, 250, 40);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("paper in the order of ");
        hintisichest.getContentPane().add(jLabel21);
        jLabel21.setBounds(50, 110, 250, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Match the numbers on the");
        hintisichest.getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 60, 250, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/hintcard.png"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(345, 280));
        hintisichest.getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 345, 280);

        hintsafekey.setLocation(new java.awt.Point(410, 322));
        hintsafekey.setLocationByPlatform(true);
        hintsafekey.setMinimumSize(new java.awt.Dimension(355, 322));
        hintsafekey.setUndecorated(true);
        hintsafekey.setResizable(false);
        hintsafekey.setSize(new java.awt.Dimension(355, 322));
        hintsafekey.getContentPane().setLayout(null);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("of the door");
        hintsafekey.getContentPane().add(jLabel18);
        jLabel18.setBounds(50, 170, 250, 40);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("There is a key behind");
        hintsafekey.getContentPane().add(jLabel19);
        jLabel19.setBounds(50, 70, 250, 40);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("the picture on the left side");
        hintsafekey.getContentPane().add(jLabel22);
        jLabel22.setBounds(50, 120, 250, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/hintcard.png"))); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(345, 280));
        hintsafekey.getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 345, 280);

        belakangfigura.setLocationByPlatform(true);
        belakangfigura.setMinimumSize(new java.awt.Dimension(499, 319));
        belakangfigura.setUndecorated(true);
        belakangfigura.setResizable(false);
        belakangfigura.setSize(new java.awt.Dimension(499, 319));
        belakangfigura.getContentPane().setLayout(null);

        safekey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/safekey.png"))); // NOI18N
        safekey.setText("jLabel10");
        safekey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        safekey.setName("safekey"); // NOI18N
        safekey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                safekeyMouseClicked(evt);
            }
        });
        belakangfigura.getContentPane().add(safekey);
        safekey.setBounds(150, 100, 190, 78);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/figura.png"))); // NOI18N
        belakangfigura.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 495, 303);

        hintarloji.setLocation(new java.awt.Point(410, 322));
        hintarloji.setLocationByPlatform(true);
        hintarloji.setMinimumSize(new java.awt.Dimension(355, 322));
        hintarloji.setUndecorated(true);
        hintarloji.setResizable(false);
        hintarloji.setSize(new java.awt.Dimension(355, 322));
        hintarloji.getContentPane().setLayout(null);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("digit of passcode");
        hintarloji.getContentPane().add(jLabel23);
        jLabel23.setBounds(50, 170, 250, 40);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("The last 2 number of");
        hintarloji.getContentPane().add(jLabel24);
        jLabel24.setBounds(50, 70, 250, 40);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("the watch is the last 2");
        hintarloji.getContentPane().add(jLabel25);
        jLabel25.setBounds(50, 120, 250, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/hintcard.png"))); // NOI18N
        jLabel26.setPreferredSize(new java.awt.Dimension(345, 280));
        hintarloji.getContentPane().add(jLabel26);
        jLabel26.setBounds(0, 0, 345, 280);

        isiarloji.setLocationByPlatform(true);
        isiarloji.setMinimumSize(new java.awt.Dimension(267, 71));
        isiarloji.setUndecorated(true);
        isiarloji.setResizable(false);
        isiarloji.setSize(new java.awt.Dimension(267, 71));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/arloji.png"))); // NOI18N
        jLabel11.setText("The watch shows 00:16");

        javax.swing.GroupLayout isiarlojiLayout = new javax.swing.GroupLayout(isiarloji.getContentPane());
        isiarloji.getContentPane().setLayout(isiarlojiLayout);
        isiarlojiLayout.setHorizontalGroup(
            isiarlojiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiarlojiLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        isiarlojiLayout.setVerticalGroup(
            isiarlojiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiarlojiLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Level 2");
        setMinimumSize(new java.awt.Dimension(1400, 789));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 789));
        getContentPane().setLayout(null);

        papan_penunjuk_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/papan gantung level 2.png"))); // NOI18N
        getContentPane().add(papan_penunjuk_1);
        papan_penunjuk_1.setBounds(1220, 0, 160, 85);

        hint_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 3.png"))); // NOI18N
        hint_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_3MouseClicked(evt);
            }
        });
        getContentPane().add(hint_3);
        hint_3.setBounds(1250, 650, 100, 80);

        hint_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 2.png"))); // NOI18N
        hint_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_2MouseClicked(evt);
            }
        });
        getContentPane().add(hint_2);
        hint_2.setBounds(1250, 650, 100, 80);

        hint_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 1.png"))); // NOI18N
        hint_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_1MouseClicked(evt);
            }
        });
        getContentPane().add(hint_1);
        hint_1.setBounds(1250, 650, 100, 80);

        hint_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 0.png"))); // NOI18N
        hint_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_0MouseClicked(evt);
            }
        });
        getContentPane().add(hint_0);
        hint_0.setBounds(1250, 650, 100, 80);

        Pintu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pintu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PintuMouseClicked(evt);
            }
        });
        getContentPane().add(Pintu);
        Pintu.setBounds(290, 160, 120, 440);

        arloji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arloji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/arloji.png"))); // NOI18N
        arloji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arloji.setName("arloji"); // NOI18N
        arloji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arlojiMouseClicked(evt);
            }
        });
        getContentPane().add(arloji);
        arloji.setBounds(210, 570, 20, 50);
        arloji.setVisible(false);

        isichestkecil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/isichestkecil .png"))); // NOI18N
        isichestkecil.setText("jLabel2");
        isichestkecil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        isichestkecil.setName("isichestkecil"); // NOI18N
        isichestkecil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isichestkecilMouseClicked(evt);
            }
        });
        getContentPane().add(isichestkecil);
        isichestkecil.setBounds(600, 620, 30, 40);
        isichestkecil.setVisible(false);

        chestopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/chestopen.png"))); // NOI18N
        chestopen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(chestopen);
        chestopen.setBounds(510, 550, 210, 176);
        chestopen.setVisible(false);

        chestclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/chestclose.png"))); // NOI18N
        chestclose.setText("jLabel3");
        chestclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chestclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chestcloseMouseClicked(evt);
            }
        });
        getContentPane().add(chestclose);
        chestclose.setBounds(550, 590, 130, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/silang.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 270, 70, 50);

        passcodedoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/passcodedoor.png"))); // NOI18N
        passcodedoor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passcodedoor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passcodedoorMouseClicked(evt);
            }
        });
        getContentPane().add(passcodedoor);
        passcodedoor.setBounds(260, 340, 30, 40);

        Timer.setFont(new java.awt.Font("Playbill", 1, 36)); // NOI18N
        Timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Timer);
        Timer.setBounds(800, 290, 150, 50);
        Timer.setText("00:00");
        second =0;
        minute =0;
        normalTimer();
        timer.start();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("= ?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 300, 70, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("The First Digit Code");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 240, 212, 32);

        safeopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/safeopen.png"))); // NOI18N
        safeopen.setText("jLabel7");
        safeopen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(safeopen);
        safeopen.setBounds(190, 530, 100, 90);
        safeopen.setVisible(false);

        safeclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/safeclose.png"))); // NOI18N
        safeclose.setText("jLabel7");
        safeclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        safeclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                safecloseMouseClicked(evt);
            }
        });
        getContentPane().add(safeclose);
        safeclose.setBounds(190, 530, 100, 90);

        figura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                figuraMouseClicked(evt);
            }
        });
        getContentPane().add(figura);
        figura.setBounds(160, 230, 60, 30);

        chestkey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/chestkey.png"))); // NOI18N
        chestkey.setText("jLabel5");
        chestkey.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chestkey.setName("chestkey"); // NOI18N
        chestkey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chestkeyMouseClicked(evt);
            }
        });
        getContentPane().add(chestkey);
        chestkey.setBounds(690, 190, 60, 50);

        Inventory_click1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click1MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click1);
        Inventory_click1.setBounds(1227, 120, 147, 121);

        Inventory_click2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click2MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click2);
        Inventory_click2.setBounds(1227, 249, 147, 121);

        Inventory_click3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click3MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click3);
        Inventory_click3.setBounds(1227, 378, 147, 121);

        Inventory_click4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click4MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click4);
        Inventory_click4.setBounds(1227, 507, 147, 121);

        i_chestkey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/i_chestkey.png"))); // NOI18N
        i_chestkey.setText("jLabel5");
        i_chestkey.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(i_chestkey);
        i_chestkey.setBounds(1350, 770, 90, 70);
        i_chestkey.setVisible(false);

        i_isichestkecil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_isichestkecil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/i_isichest.png"))); // NOI18N
        i_isichestkecil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(i_isichestkecil);
        i_isichestkecil.setBounds(1340, 760, 110, 90);
        i_isichestkecil.setVisible(false);

        i_arloji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_arloji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/i_arloji.png"))); // NOI18N
        i_arloji.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(i_arloji);
        i_arloji.setBounds(1360, 780, 70, 50);
        i_arloji.setVisible(false);

        i_safekey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/i_safekey.png"))); // NOI18N
        i_safekey.setText("jLabel2");
        i_safekey.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(i_safekey);
        i_safekey.setBounds(1350, 780, 100, 60);
        i_safekey.setVisible(false);

        Invetory_box1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box1MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box1);
        Invetory_box1.setBounds(1228, 121, 145, 119);

        Invetory_box2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box2MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box2);
        Invetory_box2.setBounds(1228, 250, 145, 119);

        Invetory_box3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box3MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box3);
        Invetory_box3.setBounds(1228, 379, 145, 119);

        Invetory_box4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box4MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box4);
        Invetory_box4.setBounds(1228, 508, 145, 119);

        Inventory_backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Inventory_background.png"))); // NOI18N
        getContentPane().add(Inventory_backgound);
        Inventory_backgound.setBounds(1200, 0, 200, 750);

        latar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level2/image/whitebedroom2.jpg"))); // NOI18N
        latar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                latarMouseClicked(evt);
            }
        });
        getContentPane().add(latar);
        latar.setBounds(0, -20, 1200, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hint_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_3MouseClicked
        Hint();
        if (available_hint) {
            hint_3.setVisible(false);
            hint_2.setVisible(true);
        }
    }//GEN-LAST:event_hint_3MouseClicked

    private void hint_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_2MouseClicked
        Hint();
        if (available_hint) {
            hint_2.setVisible(false);
            hint_1.setVisible(true);
        }
    }//GEN-LAST:event_hint_2MouseClicked

    private void hint_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_1MouseClicked
        Hint();
        if (available_hint) {
            hint_1.setVisible(false);
            hint_0.setVisible(true);
        }
    }//GEN-LAST:event_hint_1MouseClicked

    private void hint_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_0MouseClicked
        JOptionPane.showMessageDialog(this, "All hints have already been used.", "Hint", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_hint_0MouseClicked

    private void PintuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PintuMouseClicked
        Passcodepintu.setVisible(true);
    }//GEN-LAST:event_PintuMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int length = passcode.getText().length();
        int number = passcode.getText().length() - 1;
        String store;

        if (length > 0) {
            StringBuilder back = new StringBuilder(passcode.getText());
            back.deleteCharAt(number);
            store = back.toString();
            passcode.setText(store);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "1");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "2");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "3");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "4");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "5");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "6");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "7");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "8");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "9");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (passcode.getText().length() < 4) {
            passcode.setText(passcode.getText() + "0");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (passcode.getText().equals("4816")) {
            Passcodepintu.setVisible(false);
            timer.stop();
            JOptionPane.showMessageDialog(this, "You Escaped!", "Congratulations!", JOptionPane.INFORMATION_MESSAGE);
            Highscore hs = new Highscore(2, username, minute*60+second);
            this.setVisible(false);
            if (clip != null) {
                clip.stop();
            }
            sl.setVisible(true);
            hs.setVisible(true);
            if (setting.isPlaying_music()) {
                main.start();
                main.loop(Clip.LOOP_CONTINUOUSLY);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Wrong Passcode!", ":(", JOptionPane.ERROR_MESSAGE);
            passcode.setText("");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void passcodedoorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passcodedoorMouseClicked
        Passcodepintu.setVisible(true);
    }//GEN-LAST:event_passcodedoorMouseClicked

    private void chestcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chestcloseMouseClicked
        if (Chestkey) {
            chestopen.setVisible(true);
            chestclose.setVisible(false);
            isichestkecil.setVisible(true);
            i.remove(chestkey);
            i_chestkey.setVisible(false);
            new_Set();
            
            javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
            temp.setVisible(false);
            click = false;
        } else {
            JOptionPane.showMessageDialog(this, "You need to find the key first", "Missing Chest Key!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_chestcloseMouseClicked

    private void isichestkecilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isichestkecilMouseClicked
        if (i.size() < 4) {
            isichestkecil.setVisible(false);
            i.add(isichestkecil);
            have.put(isichestkecil, true);
            i_isichestkecil.setVisible(true);
            i_isichestkecil.setLocation(1250, coord_y[i.size()]);
            new_Set();
        }
    }//GEN-LAST:event_isichestkecilMouseClicked

    private void safecloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_safecloseMouseClicked
        if (Safekey) {
            safeopen.setVisible(true);
            safeclose.setVisible(false);
            arloji.setVisible(true);
            i.remove(safekey);
            i_safekey.setVisible(false);
            new_Set();
            
            javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
            temp.setVisible(false);
            click = false;
        } else {
            JOptionPane.showMessageDialog(this, "You need to find the key first", "Missing Safe Key!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_safecloseMouseClicked

    private void latarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latarMouseClicked
        Passcodepintu.setVisible(false);
        isichest.setVisible(false);
        hintchestkey.setVisible(false);
        hintsafekey.setVisible(false);
        belakangfigura.setVisible(false);
        hintarloji.setVisible(false);
        isiarloji.setVisible(false);
    }//GEN-LAST:event_latarMouseClicked

    private void figuraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_figuraMouseClicked
        belakangfigura.setVisible(true);
    }//GEN-LAST:event_figuraMouseClicked

    private void safekeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_safekeyMouseClicked
        if (i.size() < 4) {
            safekey.setVisible(false);
            i.add(safekey);
            have.put(safekey, true);
            i_safekey.setVisible(true);
            i_safekey.setLocation(1250, coord_y[i.size()]);
            new_Set();
        }
    }//GEN-LAST:event_safekeyMouseClicked

    private void Inventory_click1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click1MouseClicked
        stay(Inventory_click1);

        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click1MouseClicked

    private void Inventory_click2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click2MouseClicked
        stay(Inventory_click2);

        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click2MouseClicked

    private void Inventory_click3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click3MouseClicked
        stay(Inventory_click3);

        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click3MouseClicked

    private void Inventory_click4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click4MouseClicked
        stay(Inventory_click4);

        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click4MouseClicked

    private void Invetory_box1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box1MouseClicked
        if (i.size() >= 0) {
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel) tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }

            if (i.get(0) == isichestkecil) {
                isichest.setVisible(true);
            } else if (i.get(0) == arloji) {
                isiarloji.setVisible(true);
            } else {
                move(Inventory_click1);
                Unselect_All();
                if (i.get(0) instanceof javax.swing.JLabel) {
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
                    Select(curr);
                }
            }

        }
    }//GEN-LAST:event_Invetory_box1MouseClicked

    private void Invetory_box2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box2MouseClicked
        if (i.size() >= 1) {
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel) tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }

            if (i.get(1) == isichestkecil) {
                isichest.setVisible(true);
            } else if (i.get(1) == arloji) {
                isiarloji.setVisible(true);
            } else {
                move(Inventory_click2);
                Unselect_All();
                if (i.get(1) instanceof javax.swing.JLabel) {
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
                    Select(curr);
                }
            }

        }
    }//GEN-LAST:event_Invetory_box2MouseClicked

    private void Invetory_box3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box3MouseClicked
        if (i.size() >= 2) {
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel) tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }

            if (i.get(2) == isichestkecil) {
                isichest.setVisible(true);
            } else if (i.get(2) == arloji) {
                isiarloji.setVisible(true);
            } else {
                move(Inventory_click3);
                Unselect_All();
                if (i.get(2) instanceof javax.swing.JLabel) {
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
                    Select(curr);
                }
            }

        }
    }//GEN-LAST:event_Invetory_box3MouseClicked

    private void Invetory_box4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box4MouseClicked
        if (i.size() >= 3) {
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel) tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }

            if (i.get(3) == isichestkecil) {
                isichest.setVisible(true);
            } else if (i.get(3) == arloji) {
                isiarloji.setVisible(true);
            } else {
                move(Inventory_click4);
                Unselect_All();
                if (i.get(3) instanceof javax.swing.JLabel) {
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
                    Select(curr);
                }
            }

        }
    }//GEN-LAST:event_Invetory_box4MouseClicked

    private void chestkeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chestkeyMouseClicked
        if (i.size() < 4) {
            chestkey.setVisible(false);
            i.add(chestkey);
            have.put(chestkey, true);
            i_chestkey.setVisible(true);
            i_chestkey.setLocation(1250, coord_y[i.size()]);
            new_Set();
        }
    }//GEN-LAST:event_chestkeyMouseClicked

    private void arlojiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arlojiMouseClicked
        if (i.size() < 4) {
            arloji.setVisible(false);
            i.add(arloji);
            have.put(arloji, true);
            i_arloji.setVisible(true);
            i_arloji.setLocation(1250, coord_y[i.size()]);
            new_Set();
        }
    }//GEN-LAST:event_arlojiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level2().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inventory_backgound;
    private javax.swing.JLabel Inventory_click1;
    private javax.swing.JLabel Inventory_click2;
    private javax.swing.JLabel Inventory_click3;
    private javax.swing.JLabel Inventory_click4;
    private javax.swing.JLabel Invetory_box1;
    private javax.swing.JLabel Invetory_box2;
    private javax.swing.JLabel Invetory_box3;
    private javax.swing.JLabel Invetory_box4;
    private javax.swing.JFrame Passcodepintu;
    private javax.swing.JLabel Pintu;
    private javax.swing.JLabel Timer;
    private javax.swing.JLabel arloji;
    private javax.swing.JFrame belakangfigura;
    private javax.swing.JLabel chestclose;
    private javax.swing.JLabel chestkey;
    private javax.swing.JLabel chestopen;
    private javax.swing.JLabel figura;
    private javax.swing.JLabel hint_0;
    private javax.swing.JLabel hint_1;
    private javax.swing.JLabel hint_2;
    private javax.swing.JLabel hint_3;
    private javax.swing.JFrame hintarloji;
    private javax.swing.JFrame hintchestkey;
    private javax.swing.JFrame hintisichest;
    private javax.swing.JFrame hintsafekey;
    private javax.swing.JLabel i_arloji;
    private javax.swing.JLabel i_chestkey;
    private javax.swing.JLabel i_isichestkecil;
    private javax.swing.JLabel i_safekey;
    private javax.swing.JFrame isiarloji;
    private javax.swing.JFrame isichest;
    private javax.swing.JLabel isichestkecil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel latar;
    private javax.swing.JLabel papan_penunjuk_1;
    private javax.swing.JTextField passcode;
    private javax.swing.JLabel passcodedoor;
    private javax.swing.JLabel safeclose;
    private javax.swing.JLabel safekey;
    private javax.swing.JLabel safeopen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Select(javax.swing.JLabel curr) {
        if (curr.getName().equals("arloji")) {
            Arloji = true;
        } else if (curr.getName().equals("safekey")) {
            Safekey = true;
        } else if (curr.getName().equals("chestkey")) {
            Chestkey = true;
        } else if (curr.getName().equals("isichestkecil")) {
            Isichestkecil = true;
        }
    }

    @Override
    public void Unselect(JLabel curr) {
        if (curr.getName().equals("arloji")) {
            Arloji = false;
        } else if (curr.getName().equals("safekey")) {
            Safekey = false;
        } else if (curr.getName().equals("chestkey")) {
            Chestkey = false;
        } else if (curr.getName().equals("isichestkecil")) {
            Isichestkecil = false;
        }
    }

    @Override
    public void Unselect_All() {
        Arloji = false;
        Safekey = false;
        Chestkey = false;
        Isichestkecil = false;
    }

    @Override
    public void move(JLabel l) {
        l.setVisible(true);
        tmp.add(l);
        click = true;
    }

    @Override
    public void stay(JLabel l) {
        l.setVisible(false);
        tmp.clear();
        click = false;
    }

    private void new_Set() {
        for (int j = 0; j < 4; j++) {
            if (i.get(j) != null) {
                if (i.get(j) == arloji) {
                    i_arloji.setLocation(1250, coord_y[j]);
                } else if (i.get(j) == isichestkecil) {
                    i_isichestkecil.setLocation(1250, coord_y[j]);
                } else if (i.get(j) == safekey) {
                    i_safekey.setLocation(1250, coord_y[j]);
                } else if (i.get(j) == chestkey) {
                    i_chestkey.setLocation(1250, coord_y[j]);
                }
            }
        }
    }

    @Override
    public void Hint() {
        if (chestkey.isVisible() && !hchestkey) {
            hintchestkey.setVisible(true);
            hchestkey = true;
        } else if (safekey.isVisible() && !hsafekey) {
            hintsafekey.setVisible(true);
            hsafekey = true;
        } else if (!chestkey.isVisible() && !isichestkecil.isVisible() && !hisichest && !chestclose.isVisible()) {
            hintisichest.setVisible(true);
            hisichest = true;
        }else if(!arloji.isVisible() && !safekey.isVisible() && !harloji && !safeclose.isVisible()){
            hintarloji.setVisible(true);
            harloji = true;
        }else{
            available_hint = false;
            JOptionPane.showMessageDialog(this, "There are no hints we can give, try to solve the existing puzzle", "Hint", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void normalTimer() {
        timer = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                second++;

                ddSecond = dFormat.format(second);
                ddMinute = dFormat.format(minute);
                Timer.setText(ddMinute + ":" + ddSecond);

                if (second == 60) {
                    second = 0;
                    minute++;

                    ddSecond = dFormat.format(second);
                    ddMinute = dFormat.format(minute);
                    Timer.setText(ddMinute + ":" + ddSecond);
                }
            }
        });
    }

    @Override
    public void Playmusic(String musiclocation) {
        try {
            File musicPath = new File(musiclocation);

            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                clip.loop(Clip.LOOP_CONTINUOUSLY);
            } else {
                System.out.println("Can't find file");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
