package pbo.Level3;

import pbo.projek.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DecimalFormat;
import javax.swing.Timer;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

public class Level3 extends javax.swing.JFrame implements Methods{
    
/**
 *
 * @author Viery Pangeran - 221116995
 */
    
    private Select_Level sl;
    private Setting setting;
    private String username;
    
    private Coding_quiz cq = new Coding_quiz();
    private Inventory i = new Inventory(username);
    private int[] coord_y = new int[]{130,260,390,520};
    private boolean click = false, pc = false, baterai = false, kabel = false, tv = false, pctv = false, pcnyala = false, flkosong = false, flprogram = false,flpakai= false;
    private Map<javax.swing.JLabel,Boolean> have = new HashMap<>();
    private ArrayList tmp = new ArrayList();
    
    /**
     * Creates new form Level3
     */
    
    public Level3() {
        initComponents();
        Playmusic("Music\\Level3.wav");
    }
    
    public Level3(String username, Select_Level sl, Clip main, Setting setting) {
        initComponents();
        this.sl = sl;
        this.main = main;
        this.setting = setting;
        this.username = username;
        if (setting.isPlaying_music()) {
            Playmusic("Music\\Level3.wav");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Baterai = new javax.swing.JLabel();
        Belakangjam = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        ipctv = new javax.swing.JLabel();
        ipcnyala = new javax.swing.JLabel();
        ipc = new javax.swing.JLabel();
        ikabel = new javax.swing.JLabel();
        ibaterai = new javax.swing.JLabel();
        if_siap_pakai = new javax.swing.JLabel();
        ifl_sudah_program = new javax.swing.JLabel();
        ifl_kosongan = new javax.swing.JLabel();
        itv = new javax.swing.JLabel();
        hint_3 = new javax.swing.JLabel();
        hint_2 = new javax.swing.JLabel();
        hint_2.setVisible(false);
        hint_1 = new javax.swing.JLabel();
        hint_1.setVisible(false);
        hint_0 = new javax.swing.JLabel();
        hint_0.setVisible(false);
        Inventory_click1 = new javax.swing.JLabel();
        Inventory_click1.setVisible(false);
        Inventory_click2 = new javax.swing.JLabel();
        Inventory_click2.setVisible(false);
        Inventory_click3 = new javax.swing.JLabel();
        Inventory_click3.setVisible(false);
        Inventory_click4 = new javax.swing.JLabel();
        Inventory_click4.setVisible(false);
        Invetory_box1 = new javax.swing.JLabel();
        Invetory_box2 = new javax.swing.JLabel();
        Invetory_box3 = new javax.swing.JLabel();
        Invetory_box4 = new javax.swing.JLabel();
        gantunganlevel = new javax.swing.JLabel();
        backgroundinventory = new javax.swing.JLabel();
        Jam = new javax.swing.JLabel();
        Fl_kosongan = new javax.swing.JLabel();
        Tv = new javax.swing.JLabel();
        Pc = new javax.swing.JLabel();
        Pintu = new javax.swing.JLabel();
        Kabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Level 3");
        setMinimumSize(new java.awt.Dimension(1520, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(2000, 789));
        getContentPane().setLayout(null);

        jButton1.setText("FLASH");
        jButton1.setVisible(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 310, 550, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/bcflash.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setVisible(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1520, 740);

        Baterai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/bateraifix.png"))); // NOI18N
        Baterai.setText("jLabel1");
        Baterai.setName("baterai"); // NOI18N
        Baterai.setVisible(false);
        Baterai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BateraiMouseClicked(evt);
            }
        });
        getContentPane().add(Baterai);
        Baterai.setBounds(760, 420, 70, 20);

        Belakangjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/belakangjamfix.png"))); // NOI18N
        Belakangjam.setVisible(false);
        Belakangjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BelakangjamMouseClicked(evt);
            }
        });
        getContentPane().add(Belakangjam);
        Belakangjam.setBounds(620, 200, 350, 350);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ups.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 380, 120, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/headeset.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1210, 540, 110, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/usbhub.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(980, 130, 170, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/lemari.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(910, 150, 300, 480);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/printer.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 580, 300, 180);

        Timer.setFont(new java.awt.Font("Playbill", 1, 36)); // NOI18N
        Timer.setForeground(new java.awt.Color(204, 255, 255));
        Timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Timer);
        Timer.setBounds(600, 140, 150, 50);
        Timer.setText("00 : 00");
        second =0;
        minute =0;
        normalTimer();
        timer.start();

        ipctv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ipctv.png"))); // NOI18N
        ipctv.setName("ipctv"); // NOI18N
        getContentPane().add(ipctv);
        ipctv.setBounds(1630, 550, 60, 60);

        ipcnyala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ipcnyala.png"))); // NOI18N
        ipcnyala.setName("ipcnyala"); // NOI18N
        getContentPane().add(ipcnyala);
        ipcnyala.setBounds(1720, 530, 60, 60);

        ipc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ipc.png"))); // NOI18N
        ipc.setText("jLabel2");
        getContentPane().add(ipc);
        ipc.setBounds(1740, 280, 60, 60);

        ikabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ikabel.png"))); // NOI18N
        ikabel.setText("jLabel3");
        getContentPane().add(ikabel);
        ikabel.setBounds(1670, 360, 60, 60);

        ibaterai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ibaterai.png"))); // NOI18N
        ibaterai.setText("jLabel1");
        getContentPane().add(ibaterai);
        ibaterai.setBounds(1610, 300, 60, 60);

        if_siap_pakai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ifl_siap_pakai.png"))); // NOI18N
        if_siap_pakai.setName("if_siap_pakai"); // NOI18N
        getContentPane().add(if_siap_pakai);
        if_siap_pakai.setBounds(1840, 520, 60, 60);

        ifl_sudah_program.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ifl_sudah_diprogram.png"))); // NOI18N
        ifl_sudah_program.setName("ifl_sudah_program"); // NOI18N
        getContentPane().add(ifl_sudah_program);
        ifl_sudah_program.setBounds(1860, 400, 60, 60);

        ifl_kosongan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/ifl_kosongan.png"))); // NOI18N
        getContentPane().add(ifl_kosongan);
        ifl_kosongan.setBounds(1760, 410, 60, 60);

        itv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/itv.png"))); // NOI18N
        getContentPane().add(itv);
        itv.setBounds(1660, 460, 60, 60);

        hint_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 3.png"))); // NOI18N
        hint_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_3MouseClicked(evt);
            }
        });
        getContentPane().add(hint_3);
        hint_3.setBounds(1370, 630, 100, 80);

        hint_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 2.png"))); // NOI18N
        hint_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_2MouseClicked(evt);
            }
        });
        getContentPane().add(hint_2);
        hint_2.setBounds(1370, 630, 100, 80);

        hint_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 1.png"))); // NOI18N
        hint_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_1MouseClicked(evt);
            }
        });
        getContentPane().add(hint_1);
        hint_1.setBounds(1370, 630, 100, 80);

        hint_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 0.png"))); // NOI18N
        hint_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_0MouseClicked(evt);
            }
        });
        getContentPane().add(hint_0);
        hint_0.setBounds(1370, 630, 100, 80);

        Inventory_click1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click1MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click1);
        Inventory_click1.setBounds(1350, 100, 147, 121);

        Inventory_click2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click2MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click2);
        Inventory_click2.setBounds(1350, 230, 147, 121);

        Inventory_click3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click3MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click3);
        Inventory_click3.setBounds(1350, 360, 147, 121);

        Inventory_click4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click4MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click4);
        Inventory_click4.setBounds(1350, 490, 147, 121);

        Invetory_box1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box1MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box1);
        Invetory_box1.setBounds(1350, 100, 145, 119);

        Invetory_box2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box2MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box2);
        Invetory_box2.setBounds(1350, 230, 145, 119);

        Invetory_box3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box3MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box3);
        Invetory_box3.setBounds(1350, 360, 145, 119);

        Invetory_box4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box4MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box4);
        Invetory_box4.setBounds(1350, 490, 145, 119);

        gantunganlevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/papan gantung level 3.png"))); // NOI18N
        getContentPane().add(gantunganlevel);
        gantunganlevel.setBounds(1340, 0, 160, 85);

        backgroundinventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Inventory_background.png"))); // NOI18N
        backgroundinventory.setText("jLabel1");
        getContentPane().add(backgroundinventory);
        backgroundinventory.setBounds(1320, 0, 200, 720);

        Jam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/jamfix.png"))); // NOI18N
        Jam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JamMouseClicked(evt);
            }
        });
        getContentPane().add(Jam);
        Jam.setBounds(1040, 10, 80, 86);

        Fl_kosongan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/fl_kosongan.png"))); // NOI18N
        Fl_kosongan.setName("fl_kosongan"); // NOI18N
        Fl_kosongan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fl_kosonganMouseClicked(evt);
            }
        });
        getContentPane().add(Fl_kosongan);
        Fl_kosongan.setBounds(860, 540, 60, 40);

        Tv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/tvfix_bsr.png"))); // NOI18N
        Tv.setName("tv"); // NOI18N
        Tv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TvMouseClicked(evt);
            }
        });
        getContentPane().add(Tv);
        Tv.setBounds(200, -10, 350, 300);

        Pc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/pcfix.png"))); // NOI18N
        Pc.setText("jLabel2");
        Pc.setName("pc"); // NOI18N
        Pc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PcMouseClicked(evt);
            }
        });
        getContentPane().add(Pc);
        Pc.setBounds(500, 410, 80, 100);

        Pintu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/pintufix.png"))); // NOI18N
        Pintu.setText("jLabel1");
        Pintu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PintuMouseClicked(evt);
            }
        });
        getContentPane().add(Pintu);
        Pintu.setBounds(610, 200, 150, 270);

        Kabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/kabelfix.png"))); // NOI18N
        Kabel.setText("jLabel3");
        Kabel.setName("kabel"); // NOI18N
        Kabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KabelMouseClicked(evt);
            }
        });
        getContentPane().add(Kabel);
        Kabel.setBounds(400, 490, 60, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level3/image/background_level3.jpg"))); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        getContentPane().add(background);
        background.setBounds(0, 0, 1520, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Timer timer;
    private int second, minute;
    private String ddSecond, ddMinute;
    private DecimalFormat dFormat = new DecimalFormat("00");
    
    @Override
    public void normalTimer() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                second++;
                ddSecond = dFormat.format(second);
                ddMinute = dFormat.format(minute);
                Timer.setText(ddMinute + " : " + ddSecond);

                if (second == 60) {
                    second = 0;
                    minute++;
                    ddSecond = dFormat.format(second);
                    ddMinute = dFormat.format(minute);
                    Timer.setText(ddMinute + " : " + ddSecond);
                }
            }
        });
    }
    
    private Clip clip;
    private Clip main;
    
    @Override
    public void Playmusic(String musiclocation) {
        try {
            File musicPath = new File(musiclocation);

            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                clip.loop(Clip.LOOP_CONTINUOUSLY);
            } else {
                System.out.println("Can't find file");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    @Override
    public void Hint() {
        if(have.containsKey(Pc) && have.containsKey(Tv) && have.containsKey(Kabel)){
            if(have.containsKey(ipctv)){
                if(have.containsKey(ipcnyala)){
                    if(have.containsKey(Fl_kosongan)){
                        if(have.containsKey(ifl_sudah_program)){
                            if(have.containsKey(Baterai)){
                                JOptionPane.showMessageDialog(this, "Gabungkan Baterai dan Flashdisk Yang Sudah Di Program, Klik Flashdisknya dan Klik Pintu");
                            }else{
                                JOptionPane.showMessageDialog(this, "Ambil Baterai di Jam");
                            }
                        }else{
                            JOptionPane.showMessageDialog(this, "Gabungkan Flashdisk dengan PC, Kerjakan dan Setelah Selesai Klik Flash");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Ambil Sebuah Flashdisk");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Gabungkan PC(pc+tv) dengan kabel untuk menyalakannya");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Gabungkan PC dan Tv(sebagai monitor)");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ambil Part-Part Untuk Merakit dan Menyalakan Sebuah PC");
        }
    }
    @Override
    public void Select(javax.swing.JLabel curr){
        if (curr.getName().equals("pc")) {
            pc = true;
        }else if(curr.getName().equals("baterai")){
            baterai = true;
        }else if (curr.getName().equals("kabel")) {
            kabel = true;
        }else if (curr.getName().equals("tv")) {
            tv = true;
        }else if(curr.getName().equals("ipctv")){
            pctv = true;
        }else if (curr.getName().equals("ipcnyala")) {
            pcnyala = true;
        }else if (curr.getName().equals("fl_kosongan")) {
            flkosong = true;
        }else if (curr.getName().equals("ifl_sudah_program")) {
            flprogram = true;
        }else if (curr.getName().equals("if_siap_pakai")) {
            flpakai = true;
        }
    }
    @Override
    public void Unselect(javax.swing.JLabel curr){
        if (curr.getName().equals("pc")) {
            System.out.println("ini pc");
            pc = true;
        }else if(curr.getName().equals("baterai")){
            baterai = true;
        }else if (curr.getName().equals("kabel")) {
            kabel = true;
        }else if (curr.getName().equals("tv")) {
            tv = true;
        }else if(curr.getName().equals("ipctv")){
            pctv = true;
        }else if (curr.getName().equals("ipcnyala")) {
            pcnyala = true;
        }else if (curr.getName().equals("fl_kosongan")) {
            flkosong = true;
        }else if (curr.getName().equals("ifl_sudah_program")) {
            flprogram = true;
        }else if (curr.getName().equals("if_siap_pakai")) {
            flpakai = true;
        }
    }
    
    @Override
    public void Unselect_All(){
        pc = false;
        baterai = false;
        kabel = false;
        tv = false;
        pctv = false;
        pcnyala = false;
        flkosong = false;
        flprogram = false;
        flpakai = false;
    }
    
    @Override
    public void move(javax.swing.JLabel l){
        l.setVisible(true);
        tmp.add(l);
        click = true;
    }
    
    @Override
    public void stay(javax.swing.JLabel l){
        l.setVisible(false);
        tmp.clear();
        click = false;
    }
    private void new_Set(){
        for (int j = 0; j < 4; j++) {
            if (i.get(j) != null) {
                if (i.get(j) == Pc) {
                    ipc.setLocation(1390, coord_y[j]);
                }else if (i.get(j) == Tv) {
                    itv.setLocation(1390, coord_y[j]);
                }else if (i.get(j) == Kabel) {
                    ikabel.setLocation(1390, coord_y[j]);
                }else if (i.get(j) == Baterai) {
                    ibaterai.setLocation(1390, coord_y[j]);
                }else if (i.get(j) == ipctv) {
                    ipctv.setLocation(1390, coord_y[j]);
                }else if (i.get(j) == ipcnyala) {
                    ipcnyala.setLocation(1390, coord_y[j]);
                }else if (i.get(j) == Fl_kosongan) {
                    ifl_kosongan.setLocation(1390, coord_y[j]);
                }else if (i.get(j) == ifl_sudah_program) {
                    ifl_sudah_program.setLocation(1390, coord_y[j]);
                }else if (i.get(j) == if_siap_pakai) {
                    if_siap_pakai.setLocation(1390, coord_y[j]);
                }
            }
        }
    }
    
    private void BateraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BateraiMouseClicked
        if(i.size()<3){
            Baterai.setLocation(2000, 2000);
            Baterai.setVisible(false);
            i.add(Baterai);
            have.put(Baterai,true);
            ibaterai.setVisible(true);
            ibaterai.setLocation(1390, coord_y[i.size()]);
        }else{
            JOptionPane.showMessageDialog(this, "Inventory Penuh", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BateraiMouseClicked

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        Baterai.setVisible(false);
        Belakangjam.setVisible(false);
    }//GEN-LAST:event_backgroundMouseClicked

    private void JamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JamMouseClicked
        Baterai.setVisible(true);
        Belakangjam.setVisible(true);
    }//GEN-LAST:event_JamMouseClicked

    private void Inventory_click1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click1MouseClicked
        stay(Inventory_click1);
        
        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click1MouseClicked

    private void Inventory_click2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click2MouseClicked
        stay(Inventory_click2);
        
        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click2MouseClicked

    private void Inventory_click3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click3MouseClicked
        stay(Inventory_click3);
        
        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click3MouseClicked

    private void Inventory_click4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click4MouseClicked
        stay(Inventory_click4);
        
        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click4MouseClicked

    private void Invetory_box1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box1MouseClicked
        int iz=0;
        if(i.size() >= 0){
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
            if (pc && i.get(iz) == Tv) {
                ipctv.setVisible(true);
                i.add(ipctv);
                have.put(ipctv, true);
                i.remove(iz);
                i.remove(Pc);
                ipc.setVisible(false);
                itv.setVisible(false);
                new_Set();
            }else if (tv && i.get(iz) == Pc) {
                ipctv.setVisible(true);
                i.add(ipctv);
                have.put(ipctv, true);
                i.remove(iz);
                i.remove(Tv);
                ipc.setVisible(false);
                itv.setVisible(false);
                new_Set();
            }else if (pctv && i.get(iz) == Kabel) {
                ipcnyala.setVisible(true);
                i.add(ipcnyala);
                have.put(ipcnyala, true);
                i.remove(iz);
                i.remove(ipctv);
                ipctv.setVisible(false);
                ikabel.setVisible(false);
                new_Set();
            }else if (kabel && i.get(iz) == ipctv) {
                ipcnyala.setVisible(true);
                i.add(ipcnyala);
                have.put(ipcnyala, true);
                i.remove(iz);
                i.remove(Kabel);
                ipctv.setVisible(false);
                ikabel.setVisible(false);
                new_Set();
            }else if (flkosong && i.get(iz) == ipcnyala) {
                cq.setVisible(true);
                jButton1.setVisible(true);
                jLabel1.setVisible(true);
            }else if (pcnyala && i.get(iz) == Fl_kosongan) {
                cq.setVisible(true);
                jButton1.setVisible(true);
                jLabel1.setVisible(true);
            }else if (baterai && i.get(iz) == ifl_sudah_program) {
                if_siap_pakai.setVisible(true);
                i.add(if_siap_pakai);
                have.put(if_siap_pakai, true);
                i.remove(iz);
                i.remove(Baterai);
                ifl_sudah_program.setVisible(false);
                ibaterai.setVisible(false);
                new_Set();
            }else if (flprogram && i.get(iz) == Baterai) {
                if_siap_pakai.setVisible(true);
                i.add(if_siap_pakai);
                have.put(if_siap_pakai, true);
                i.remove(iz);
                i.remove(ifl_sudah_program);
                ifl_sudah_program.setVisible(false);
                ibaterai.setVisible(false);
                new_Set();
            }else{
                move(Inventory_click1);
                Unselect_All();
                if(i.get(iz) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(iz);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_Invetory_box1MouseClicked

    private void Invetory_box2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box2MouseClicked
        int iz=1;
        if(i.size() >= 0){
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
            if (pc && i.get(iz) == Tv) {
                ipctv.setVisible(true);
                i.add(ipctv);
                have.put(ipctv, true);
                i.remove(iz);
                i.remove(Pc);
                ipc.setVisible(false);
                itv.setVisible(false);
                new_Set();
            }else if (tv && i.get(iz) == Pc) {
                ipctv.setVisible(true);
                i.add(ipctv);
                have.put(ipctv, true);
                i.remove(iz);
                i.remove(Tv);
                ipc.setVisible(false);
                itv.setVisible(false);
                new_Set();
            }else if (pctv && i.get(iz) == Kabel) {
                ipcnyala.setVisible(true);
                i.add(ipcnyala);
                have.put(ipcnyala, true);
                i.remove(iz);
                i.remove(ipctv);
                ipctv.setVisible(false);
                ikabel.setVisible(false);
                new_Set();
            }else if (kabel && i.get(iz) == ipctv) {
                ipcnyala.setVisible(true);
                i.add(ipcnyala);
                have.put(ipcnyala, true);
                i.remove(iz);
                i.remove(Kabel);
                ipctv.setVisible(false);
                ikabel.setVisible(false);
                new_Set();
            }else if (flkosong && i.get(iz) == ipcnyala) {
                cq.setVisible(true);
                jButton1.setVisible(true);
                jLabel1.setVisible(true);
            }else if (pcnyala && i.get(iz) == Fl_kosongan) {
                cq.setVisible(true);
                jButton1.setVisible(true);
                jLabel1.setVisible(true);
            }else if (baterai && i.get(iz) == ifl_sudah_program) {
                if_siap_pakai.setVisible(true);
                i.add(if_siap_pakai);
                have.put(if_siap_pakai, true);
                i.remove(iz);
                i.remove(Baterai);
                ifl_sudah_program.setVisible(false);
                ibaterai.setVisible(false);
                new_Set();
            }else if (flprogram && i.get(iz) == Baterai) {
                if_siap_pakai.setVisible(true);
                i.add(if_siap_pakai);
                have.put(if_siap_pakai, true);
                i.remove(iz);
                i.remove(ifl_sudah_program);
                ifl_sudah_program.setVisible(false);
                ibaterai.setVisible(false);
                new_Set();
            }else{
                move(Inventory_click2);
                Unselect_All();
                if(i.get(iz) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(iz);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_Invetory_box2MouseClicked

    private void Invetory_box3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box3MouseClicked
       int iz=2;
        if(i.size() >= 0){
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
            if (pc && i.get(iz) == Tv) {
                ipctv.setVisible(true);
                i.add(ipctv);
                have.put(ipctv, true);
                i.remove(iz);
                i.remove(Pc);
                ipc.setVisible(false);
                itv.setVisible(false);
                new_Set();
            }else if (tv && i.get(iz) == Pc) {
                ipctv.setVisible(true);
                i.add(ipctv);
                have.put(ipctv, true);
                i.remove(iz);
                i.remove(Tv);
                ipc.setVisible(false);
                itv.setVisible(false);
                new_Set();
            }else if (pctv && i.get(iz) == Kabel) {
                ipcnyala.setVisible(true);
                i.add(ipcnyala);
                have.put(ipcnyala, true);
                i.remove(iz);
                i.remove(ipctv);
                ipctv.setVisible(false);
                ikabel.setVisible(false);
                new_Set();
            }else if (kabel && i.get(iz) == ipctv) {
                ipcnyala.setVisible(true);
                i.add(ipcnyala);
                have.put(ipcnyala, true);
                i.remove(iz);
                i.remove(Kabel);
                ipctv.setVisible(false);
                ikabel.setVisible(false);
                new_Set();
            }else if (flkosong && i.get(iz) == ipcnyala) {
                cq.setVisible(true);
                jButton1.setVisible(true);
                jLabel1.setVisible(true);
            }else if (pcnyala && i.get(iz) == Fl_kosongan) {
                cq.setVisible(true);
                jButton1.setVisible(true);
                jLabel1.setVisible(true);
            }else if (baterai && i.get(iz) == ifl_sudah_program) {
                if_siap_pakai.setVisible(true);
                i.add(if_siap_pakai);
                have.put(if_siap_pakai, true);
                i.remove(iz);
                i.remove(Baterai);
                ifl_sudah_program.setVisible(false);
                ibaterai.setVisible(false);
                new_Set();
            }else if (flprogram && i.get(iz) == Baterai) {
                if_siap_pakai.setVisible(true);
                i.add(if_siap_pakai);
                have.put(if_siap_pakai, true);
                i.remove(iz);
                i.remove(ifl_sudah_program);
                ifl_sudah_program.setVisible(false);
                ibaterai.setVisible(false);
                new_Set();
            }else{
                move(Inventory_click3);
                Unselect_All();
                if(i.get(iz) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(iz);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_Invetory_box3MouseClicked

    private void Invetory_box4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box4MouseClicked
        int iz=3;
        if(i.size() >= 0){
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
            if (pc && i.get(iz) == Tv) {
                ipctv.setVisible(true);
                i.add(ipctv);
                have.put(ipctv, true);
                i.remove(iz);
                i.remove(Pc);
                ipc.setVisible(false);
                itv.setVisible(false);
                new_Set();
            }else if (tv && i.get(iz) == Pc) {
                ipctv.setVisible(true);
                i.add(ipctv);
                have.put(ipctv, true);
                i.remove(iz);
                i.remove(Tv);
                ipc.setVisible(false);
                itv.setVisible(false);
                new_Set();
            }else if (pctv && i.get(iz) == Kabel) {
                ipcnyala.setVisible(true);
                i.add(ipcnyala);
                have.put(ipcnyala, true);
                i.remove(iz);
                i.remove(ipctv);
                ipctv.setVisible(false);
                ikabel.setVisible(false);
                new_Set();
            }else if (kabel && i.get(iz) == ipctv) {
                ipcnyala.setVisible(true);
                i.add(ipcnyala);
                have.put(ipcnyala, true);
                i.remove(iz);
                i.remove(Kabel);
                ipctv.setVisible(false);
                ikabel.setVisible(false);
                new_Set();
            }else if (flkosong && i.get(iz) == ipcnyala) {
                cq.setVisible(true);
                jButton1.setVisible(true);
                jLabel1.setVisible(true);
            }else if (pcnyala && i.get(iz) == Fl_kosongan) {
                cq.setVisible(true);
                jButton1.setVisible(true);
                jLabel1.setVisible(true);
            }else if (baterai && i.get(iz) == ifl_sudah_program) {
                if_siap_pakai.setVisible(true);
                i.add(if_siap_pakai);
                have.put(if_siap_pakai, true);
                i.remove(iz);
                i.remove(Baterai);
                ifl_sudah_program.setVisible(false);
                ibaterai.setVisible(false);
                new_Set();
            }else if (flprogram && i.get(iz) == Baterai) {
                if_siap_pakai.setVisible(true);
                i.add(if_siap_pakai);
                have.put(if_siap_pakai, true);
                i.remove(iz);
                i.remove(ifl_sudah_program);
                ifl_sudah_program.setVisible(false);
                ibaterai.setVisible(false);
                new_Set();
            }else{
                move(Inventory_click4);
                Unselect_All();
                if(i.get(iz) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(iz);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_Invetory_box4MouseClicked

    private void hint_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_3MouseClicked
        hint_3.setVisible(false);
        hint_2.setVisible(true);
        Hint();
    }//GEN-LAST:event_hint_3MouseClicked

    private void hint_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_2MouseClicked
        hint_2.setVisible(false);
        hint_1.setVisible(true);
        Hint();
    }//GEN-LAST:event_hint_2MouseClicked

    private void hint_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_1MouseClicked
        hint_1.setVisible(false);
        hint_0.setVisible(true);
        Hint();
    }//GEN-LAST:event_hint_1MouseClicked

    private void hint_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_0MouseClicked
        JOptionPane.showMessageDialog(this, "Hint sudah habis", "Hint", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_hint_0MouseClicked

    private void KabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KabelMouseClicked
        if(i.size()<3){
            Kabel.setVisible(false);
            i.add(Kabel);
            have.put(Kabel,true);
            ikabel.setVisible(true);
            ikabel.setLocation(1390, coord_y[i.size()]);
        }else{
            JOptionPane.showMessageDialog(this, "Inventory Penuh", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_KabelMouseClicked

    private void PcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PcMouseClicked
        if(i.size()<3){
            Pc.setVisible(false);
            i.add(Pc);
            have.put(Pc,true);
            ipc.setVisible(true);
            ipc.setLocation(1390, coord_y[i.size()]);
        }else{
            JOptionPane.showMessageDialog(this, "Inventory Penuh", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_PcMouseClicked

    private void Fl_kosonganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fl_kosonganMouseClicked
        if(i.size()<3){
            Fl_kosongan.setVisible(false);
            i.add(Fl_kosongan);
            have.put(Fl_kosongan,true);
            ifl_kosongan.setVisible(true);
            ifl_kosongan.setLocation(1390, coord_y[i.size()]);
        }else{
            JOptionPane.showMessageDialog(this, "Inventory Penuh", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Fl_kosonganMouseClicked

    private void TvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TvMouseClicked
        if(i.size()<3){
            Tv.setVisible(false);
            i.add(Tv);
            have.put(Tv,true);
            itv.setVisible(true);
            itv.setLocation(1390, coord_y[i.size()]);
        }else{
            JOptionPane.showMessageDialog(this, "Inventory Penuh", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TvMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(cq.fl_sudah_program_selesai == 1){
            ifl_sudah_program.setVisible(true);
            i.add(ifl_sudah_program);
            have.put(ifl_sudah_program, true);
            i.remove(Fl_kosongan);
            i.remove(ipcnyala);
            ipcnyala.setVisible(false);
            ifl_kosongan.setVisible(false);
            new_Set(); 
            jLabel1.setVisible(false);
            jButton1.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Tidak Dapat Melakukan Aksi!", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void BelakangjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BelakangjamMouseClicked
        Baterai.setVisible(false);
        Belakangjam.setVisible(false);
    }//GEN-LAST:event_BelakangjamMouseClicked

    private void PintuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PintuMouseClicked
        if(flpakai){
            if (clip != null) {
                clip.stop();
            }
            if (setting.isPlaying_music()) {
                main.start();
                main.loop(Clip.LOOP_CONTINUOUSLY);
            }
            sl.setVisible(true);
            this.setVisible(false);
            Highscore hs = new Highscore(3, username, minute*60+second);
            hs.setVisible(true);
            JOptionPane.showMessageDialog(this, "Selamat!", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Dibutuhkan Kunci Digital!", "Hint", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_PintuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baterai;
    private javax.swing.JLabel Belakangjam;
    private javax.swing.JLabel Fl_kosongan;
    private javax.swing.JLabel Inventory_click1;
    private javax.swing.JLabel Inventory_click2;
    private javax.swing.JLabel Inventory_click3;
    private javax.swing.JLabel Inventory_click4;
    private javax.swing.JLabel Invetory_box1;
    private javax.swing.JLabel Invetory_box2;
    private javax.swing.JLabel Invetory_box3;
    private javax.swing.JLabel Invetory_box4;
    private javax.swing.JLabel Jam;
    private javax.swing.JLabel Kabel;
    private javax.swing.JLabel Pc;
    private javax.swing.JLabel Pintu;
    private javax.swing.JLabel Timer;
    private javax.swing.JLabel Tv;
    private javax.swing.JLabel background;
    private javax.swing.JLabel backgroundinventory;
    private javax.swing.JLabel gantunganlevel;
    private javax.swing.JLabel hint_0;
    private javax.swing.JLabel hint_1;
    private javax.swing.JLabel hint_2;
    private javax.swing.JLabel hint_3;
    private javax.swing.JLabel ibaterai;
    private javax.swing.JLabel if_siap_pakai;
    private javax.swing.JLabel ifl_kosongan;
    private javax.swing.JLabel ifl_sudah_program;
    private javax.swing.JLabel ikabel;
    private javax.swing.JLabel ipc;
    private javax.swing.JLabel ipcnyala;
    private javax.swing.JLabel ipctv;
    private javax.swing.JLabel itv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
