package pbo.Level4;

import pbo.projek.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DecimalFormat;
import javax.swing.Timer;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

public class Level4 extends javax.swing.JFrame implements Methods {

/**
 *
 * @author Kenneth Joseph Rudyanto - 221116968
 */
    
    private Select_Level sl;
    private Setting setting;
    private String username;
    private boolean gunting = false, obeng = false, palu = false, crowbar = false, palinggis = false, toilet2 = false; 
    
    private String[] hint = new String[]{
        "Ambil gunting terlebih dahulu",
        "Gunakan gunting untuk mengambil obeng",
        "Gunakan obeng untuk membuka mesin cuci",
        "Gabungkan palu dan crowbar",
        "Gunakan gabungan dari palu dan crowbar untuk membuka toilet",
        "Keluar ruangan melalui lubang toilet"
    };
    
    //INVENTORY
    private Inventory i = new Inventory(username);
    private boolean click = false, Chestkey = false, Safekey = false, Arloji = false, Isichestkecil = false;
    private Map<javax.swing.JLabel, Boolean> have = new HashMap<>();
    private int[] coord_y = new int[]{140, 270, 405, 535};
    private ArrayList tmp = new ArrayList();
    
//====================================================================================================================================================
    private Timer timer;
    private int second, minute;
    private String ddSecond, ddMinute;
    private DecimalFormat dFormat = new DecimalFormat("00");
    // Timer
    public void normalTimer() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                second++;
                ddSecond = dFormat.format(second);
                ddMinute = dFormat.format(minute);
                Timer.setText(ddMinute + " : " + ddSecond);

                if (second == 60) {
                    second = 0;
                    minute++;
                    ddSecond = dFormat.format(second);
                    ddMinute = dFormat.format(minute);
                    Timer.setText(ddMinute + " : " + ddSecond);
                }
            }
        });
    }
//=====================================================================================================================================================    
    // Music
    private Clip clip;
    private Clip main;
    public void Playmusic(String musiclocation) {
        try {
            File musicPath = new File(musiclocation);

            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                clip.loop(Clip.LOOP_CONTINUOUSLY);
            } else {
                System.out.println("Can't find file");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
//=====================================================================================================================================================    
    
    private void make_palinggis(int x, javax.swing.JLabel z){
        Palinggis.setVisible(true);
        i.add(Palinggis);
        have.put(Palinggis, true);
        i.remove(x);
        i.remove(z);
        Palu.setVisible(false);
        Crowbar.setVisible(false);
        new_Set();
    }
    
    private boolean cek(javax.swing.JLabel item){
        for (Map.Entry<JLabel, Boolean> entry : have.entrySet()) {
            JLabel key = entry.getKey();
            Boolean value = entry.getValue();
            if (key == item) {
                return value;
            }
        }
        return false;
    }
    
    /**
     * Creates new form Level4
     */
    public Level4() {
        initComponents();
        Playmusic("Music//Level4.wav");
    }
    
    public Level4(String username, Select_Level sl, Clip main, Setting setting) {
        initComponents();
        this.sl = sl;
        this.main = main;
        this.setting = setting;
        this.username = username;
        if (setting.isPlaying_music()) {
            Playmusic("Music\\Level4.wav");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        papan_penunjuk_1 = new javax.swing.JLabel();
        hint_3 = new javax.swing.JLabel();
        hint_2 = new javax.swing.JLabel();
        hint_2.setVisible(false);
        hint_1 = new javax.swing.JLabel();
        hint_1.setVisible(false);
        hint_0 = new javax.swing.JLabel();
        hint_0.setVisible(false);
        Inventory_click1 = new javax.swing.JLabel();
        Inventory_click1.setVisible(false);
        Inventory_click2 = new javax.swing.JLabel();
        Inventory_click2.setVisible(false);
        Inventory_click3 = new javax.swing.JLabel();
        Inventory_click3.setVisible(false);
        Inventory_click4 = new javax.swing.JLabel();
        Inventory_click4.setVisible(false);
        Palu = new javax.swing.JLabel();
        Obeng = new javax.swing.JLabel();
        Crowbar = new javax.swing.JLabel();
        Palinggis = new javax.swing.JLabel();
        Gunting = new javax.swing.JLabel();
        Invetory_box1 = new javax.swing.JLabel();
        Invetory_box2 = new javax.swing.JLabel();
        Invetory_box3 = new javax.swing.JLabel();
        Invetory_box4 = new javax.swing.JLabel();
        Inventory_backgound = new javax.swing.JLabel();
        toilet = new javax.swing.JLabel();
        lubang_toilet = new javax.swing.JLabel();
        mesin_cuci = new javax.swing.JLabel();
        keranjang_baju = new javax.swing.JLabel();
        tali = new javax.swing.JLabel();
        sofa = new javax.swing.JLabel();
        lampu = new javax.swing.JLabel();
        karpet = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Level 4");
        setMinimumSize(new java.awt.Dimension(1400, 788));
        setResizable(false);
        getContentPane().setLayout(null);

        papan_penunjuk_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/papan gantung level 4.png"))); // NOI18N
        getContentPane().add(papan_penunjuk_1);
        papan_penunjuk_1.setBounds(1220, 0, 160, 85);

        hint_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 3.png"))); // NOI18N
        hint_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_3MouseClicked(evt);
            }
        });
        getContentPane().add(hint_3);
        hint_3.setBounds(1250, 650, 100, 80);

        hint_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 2.png"))); // NOI18N
        hint_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_2MouseClicked(evt);
            }
        });
        getContentPane().add(hint_2);
        hint_2.setBounds(1250, 650, 100, 80);

        hint_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 1.png"))); // NOI18N
        hint_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_1MouseClicked(evt);
            }
        });
        getContentPane().add(hint_1);
        hint_1.setBounds(1250, 650, 100, 80);

        hint_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Hint 0.png"))); // NOI18N
        hint_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hint_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hint_0MouseClicked(evt);
            }
        });
        getContentPane().add(hint_0);
        hint_0.setBounds(1250, 650, 100, 80);

        Inventory_click1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click1MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click1);
        Inventory_click1.setBounds(1227, 120, 147, 121);

        Inventory_click2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click2MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click2);
        Inventory_click2.setBounds(1227, 249, 147, 121);

        Inventory_click3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click3MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click3);
        Inventory_click3.setBounds(1227, 378, 147, 121);

        Inventory_click4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory click.png"))); // NOI18N
        Inventory_click4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventory_click4MouseClicked(evt);
            }
        });
        getContentPane().add(Inventory_click4);
        Inventory_click4.setBounds(1227, 507, 147, 121);

        Palu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/Emoji_hammer-removebg-preview.png"))); // NOI18N
        Palu.setName("palu"); // NOI18N
        Palu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaluMouseClicked(evt);
            }
        });
        getContentPane().add(Palu);
        Palu.setBounds(570, 590, 80, 80);

        Obeng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/pngtree-screwdriver-png-image_2444208-removebg-preview.png"))); // NOI18N
        Obeng.setName("obeng"); // NOI18N
        Obeng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObengMouseClicked(evt);
            }
        });
        getContentPane().add(Obeng);
        Obeng.setBounds(180, 80, 90, 50);

        Crowbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/pngtree-installation-tool-crowbar-illustration-image_1425203-removebg-preview.png"))); // NOI18N
        Crowbar.setName("crowbar"); // NOI18N
        Crowbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrowbarMouseClicked(evt);
            }
        });
        getContentPane().add(Crowbar);
        Crowbar.setBounds(120, 440, 90, 40);
        Crowbar.setVisible(false);

        Palinggis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/Screenshot__272_-removebg-preview (1).png"))); // NOI18N
        Palinggis.setName("palinggis"); // NOI18N
        getContentPane().add(Palinggis);
        Palinggis.setBounds(770, 480, 100, 80);
        Palinggis.setVisible(false);

        Gunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/scissor-removebg-preview.png"))); // NOI18N
        Gunting.setName("gunting"); // NOI18N
        Gunting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuntingMouseClicked(evt);
            }
        });
        getContentPane().add(Gunting);
        Gunting.setBounds(590, 430, 70, 100);

        Invetory_box1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box1MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box1);
        Invetory_box1.setBounds(1228, 121, 145, 119);

        Invetory_box2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box2MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box2);
        Invetory_box2.setBounds(1228, 250, 145, 119);

        Invetory_box3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box3MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box3);
        Invetory_box3.setBounds(1228, 379, 145, 119);

        Invetory_box4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/inventory box.png"))); // NOI18N
        Invetory_box4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Invetory_box4MouseClicked(evt);
            }
        });
        getContentPane().add(Invetory_box4);
        Invetory_box4.setBounds(1228, 508, 145, 119);

        Inventory_backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Inventory_background.png"))); // NOI18N
        getContentPane().add(Inventory_backgound);
        Inventory_backgound.setBounds(1200, 0, 200, 750);

        toilet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/toilet.png"))); // NOI18N
        toilet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toiletMouseClicked(evt);
            }
        });
        getContentPane().add(toilet);
        toilet.setBounds(990, 390, 160, 200);

        lubang_toilet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/broken-orange-.png"))); // NOI18N
        lubang_toilet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lubang_toiletMouseClicked(evt);
            }
        });
        getContentPane().add(lubang_toilet);
        lubang_toilet.setBounds(1000, 470, 120, 100);

        mesin_cuci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/washing-machine-removebg-preview.png"))); // NOI18N
        mesin_cuci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesin_cuciMouseClicked(evt);
            }
        });
        getContentPane().add(mesin_cuci);
        mesin_cuci.setBounds(50, 370, 210, 190);

        keranjang_baju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/clothes-5709419_1280-removebg-preview.png"))); // NOI18N
        getContentPane().add(keranjang_baju);
        keranjang_baju.setBounds(260, 470, 90, 90);

        tali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/rope.png"))); // NOI18N
        getContentPane().add(tali);
        tali.setBounds(180, 0, 110, 110);

        sofa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/sofa-removebg-preview.png"))); // NOI18N
        sofa.setText("jLabel1");
        getContentPane().add(sofa);
        sofa.setBounds(440, 400, 380, 170);

        lampu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/lampu-removebg-preview-removebg-preview.png"))); // NOI18N
        getContentPane().add(lampu);
        lampu.setBounds(1020, -70, 170, 260);

        karpet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/carpet-removebg-preview.png"))); // NOI18N
        karpet.setText("jLabel1");
        getContentPane().add(karpet);
        karpet.setBounds(190, 570, 860, 120);

        Timer.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Timer.setName("timer"); // NOI18N
        getContentPane().add(Timer);
        Timer.setBounds(540, 60, 130, 60);
        Timer.setText("00:00");
        second =0;
        minute =0;
        normalTimer();
        timer.start();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/banteng-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 160, 260, 250);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/Level4/image/240_F_191969493_LMt2BmOMVbEBhlCiBGhJKQdjb8sc1YXD.jpg"))); // NOI18N
        background.setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().add(background);
        background.setBounds(0, 0, 1200, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hint_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_3MouseClicked
        hint_3.setVisible(false);
        hint_2.setVisible(true);
        Hint();
    }//GEN-LAST:event_hint_3MouseClicked

    private void hint_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_2MouseClicked
        hint_2.setVisible(false);
        hint_1.setVisible(true);
        Hint();
    }//GEN-LAST:event_hint_2MouseClicked

    private void hint_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_1MouseClicked
        hint_1.setVisible(false);
        hint_0.setVisible(true);
        Hint();
    }//GEN-LAST:event_hint_1MouseClicked

    private void hint_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hint_0MouseClicked
        JOptionPane.showMessageDialog(this, "Hint sudah habis", "Hint", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_hint_0MouseClicked

    private void Inventory_click1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click1MouseClicked
        stay(Inventory_click1);

        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click1MouseClicked

    private void Inventory_click2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click2MouseClicked
        stay(Inventory_click2);

        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click2MouseClicked

    private void Inventory_click3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click3MouseClicked
        stay(Inventory_click3);

        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click3MouseClicked

    private void Inventory_click4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventory_click4MouseClicked
        stay(Inventory_click4);

        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
        Unselect(curr);
    }//GEN-LAST:event_Inventory_click4MouseClicked

    private void Invetory_box1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box1MouseClicked
        if(i.size() >= 0){
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
            if (palu && i.get(0) == Crowbar) {
                make_palinggis(0, Palu);
            }else if (crowbar && i.get(0) == Palu) {
                make_palinggis(0, Crowbar);
            }else{
                move(Inventory_click1);
                Unselect_All();
                if(i.get(0) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_Invetory_box1MouseClicked

    private void Invetory_box2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box2MouseClicked
        if(i.size() >= 1){
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
            if (palu && i.get(1) == Crowbar) {
                make_palinggis(1, Palu);
            }else if (crowbar && i.get(1) == Palu) {
                make_palinggis(1, Crowbar);
            }else{
                move(Inventory_click2);
                Unselect_All();
                if(i.get(1) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_Invetory_box2MouseClicked

    private void Invetory_box3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box3MouseClicked
        if(i.size() >= 2){
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
            if (palu && i.get(2) == Crowbar) {
                make_palinggis(2, Palu);
            }else if (crowbar && i.get(2) == Palu) {
                make_palinggis(2, Crowbar);
            }else{
                move(Inventory_click3);
                Unselect_All();
                if(i.get(2) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_Invetory_box3MouseClicked

    private void Invetory_box4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invetory_box4MouseClicked
        if(i.size() >= 3){
            if (click) {
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
            if (palu && i.get(3) == Crowbar) {
                make_palinggis(3, Palu);
            }else if (crowbar && i.get(3) == Palu) {
                make_palinggis(3, Crowbar);
            }else{
                move(Inventory_click4);
                Unselect_All();
                if(i.get(3) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_Invetory_box4MouseClicked

    private void toiletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toiletMouseClicked
        if (palinggis) {
            Palinggis.setVisible(false);
            i.remove(Palinggis);
            new_Set();
            toilet.setLocation(890, 390);
            toilet2 = true;
            
            javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
            temp.setVisible(false);
            click = false;
        }
    }//GEN-LAST:event_toiletMouseClicked

    private void GuntingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuntingMouseClicked
        if(i.size() < 3 && !cek(Gunting)){
            i.add(Gunting);
            have.put(Gunting, true);
            Gunting.setLocation(1250, coord_y[i.size()]);
        }else{
            if(i.get(0) == Gunting){
                if(i.size() >= 0){
                    if (click) {
                        javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                        temp.setVisible(false);
                        click = false;
                    }
                    move(Inventory_click1);
                    Unselect_All();
                    if(i.get(0) instanceof javax.swing.JLabel){
                        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
                        Select(curr);
                    }
                }
            }else if(i.get(1) == Gunting){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                move(Inventory_click2);
                Unselect_All();
                if(i.get(1) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
                    Select(curr);
                }
            }else if(i.get(2) == Gunting){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                move(Inventory_click3);
                Unselect_All();
                if(i.get(2) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
                    Select(curr);
                }
            }else if(i.get(3) == Gunting){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                move(Inventory_click4);
                Unselect_All();
                if(i.get(3) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_GuntingMouseClicked

    private void PaluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaluMouseClicked
        if(i.size() < 3 && !cek(Palu)){
                i.add(Palu);
                have.put(Palu, true);
                Palu.setLocation(1250, coord_y[i.size()]);
            }else{
                if(i.get(0) == Palu){
                    if(i.size() >= 0){
                        if (click) {
                            javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                            temp.setVisible(false);
                            click = false;
                        }
                        if (crowbar) {
                            make_palinggis(0, Crowbar);
                        }else{
                            move(Inventory_click1);
                            Unselect_All();
                            if(i.get(0) instanceof javax.swing.JLabel){
                                javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
                                Select(curr);
                            }
                        }
                    }
                }else if(i.get(1) == Palu){
                    if (click) {
                        javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                        temp.setVisible(false);
                        click = false;
                    }
                    if (crowbar) {
                        make_palinggis(1, Crowbar);
                    }else{
                        move(Inventory_click2);
                        Unselect_All();
                        if(i.get(1) instanceof javax.swing.JLabel){
                            javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
                            Select(curr);
                        }
                    }
                }else if(i.get(2) == Palu){
                    if (click) {
                        javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                        temp.setVisible(false);
                        click = false;
                    }
                    if (crowbar) {
                        make_palinggis(2, Crowbar);
                    }else{
                        move(Inventory_click3);
                        Unselect_All();
                        if(i.get(2) instanceof javax.swing.JLabel){
                            javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
                            Select(curr);
                        }
                    }            
                }else if(i.get(3) == Palu){
                    if (click) {
                        javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                        temp.setVisible(false);
                        click = false;
                    }
                    if (crowbar) {
                        make_palinggis(3, Crowbar);
                    }else{
                        move(Inventory_click4);
                        Unselect_All();
                        if(i.get(3) instanceof javax.swing.JLabel){
                            javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
                            Select(curr);
                        }
                    }
                }
            }
    }//GEN-LAST:event_PaluMouseClicked

    private void ObengMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObengMouseClicked
        if(gunting){
            if(i.size() < 3 && !cek(Obeng)){
                i.add(Obeng);
                have.put(Obeng, true);
                Obeng.setLocation(1250, coord_y[i.size()]);
                gunting = false;
                Gunting.setVisible(false);
                i.remove(Gunting);
                new_Set();
                
                javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                temp.setVisible(false);
                click = false;
            }
        }else{
            if(i.get(0) == Obeng){
                if(i.size() >= 0){
                    if (click) {
                        javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                        temp.setVisible(false);
                        click = false;
                    }
                    move(Inventory_click1);
                    Unselect_All();
                    if(i.get(0) instanceof javax.swing.JLabel){
                        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
                        Select(curr);
                    }
                }
            }else if(i.get(1) == Obeng){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                move(Inventory_click2);
                Unselect_All();
                if(i.get(1) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
                    Select(curr);
                }
            }else if(i.get(2) == Obeng){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                move(Inventory_click3);
                Unselect_All();
                if(i.get(2) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
                    Select(curr);
                }
            }else if(i.get(3) == Obeng){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                move(Inventory_click4);
                Unselect_All();
                if(i.get(3) instanceof javax.swing.JLabel){
                    javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
                    Select(curr);
                }
            }
        }
    }//GEN-LAST:event_ObengMouseClicked

    private void mesin_cuciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesin_cuciMouseClicked
        if (obeng) {           
            Obeng.setVisible(false);
            i.remove(Obeng);
            new_Set();
            Crowbar.setVisible(true);

            javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
            temp.setVisible(false);
            click = false;
        }
    }//GEN-LAST:event_mesin_cuciMouseClicked

    private void CrowbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrowbarMouseClicked
        if(i.size() < 3 && !cek(Crowbar)){
            i.add(Crowbar);
            have.put(Crowbar, true);
            Crowbar.setLocation(1250, coord_y[i.size()]);
        }else{
            if(i.get(0) == Crowbar){
                if(i.size() >= 0){
                    if (click) {
                        javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                        temp.setVisible(false);
                        click = false;
                    }
                    if (palu) {
                        make_palinggis(0, Palu);
                    }else{
                        move(Inventory_click1);
                        Unselect_All();
                        if(i.get(0) instanceof javax.swing.JLabel){
                            javax.swing.JLabel curr = (javax.swing.JLabel) i.get(0);
                            Select(curr);
                        }
                    }
                }
            }else if(i.get(1) == Crowbar){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                if (palu) {
                    make_palinggis(1, Palu);
                }else{
                    move(Inventory_click2);
                    Unselect_All();
                    if(i.get(1) instanceof javax.swing.JLabel){
                        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(1);
                        Select(curr);
                    }
                }
            }else if(i.get(2) == Crowbar){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                if (palu) {
                    make_palinggis(2, Palu);
                }else{
                    move(Inventory_click3);
                    Unselect_All();
                    if(i.get(2) instanceof javax.swing.JLabel){
                        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(2);
                        Select(curr);
                    }
                }
            }else if(i.get(3) == Crowbar){
                if (click) {
                    javax.swing.JLabel temp = (javax.swing.JLabel)tmp.remove(0);
                    temp.setVisible(false);
                    click = false;
                }
                if (palu) {
                    make_palinggis(3, Palu);
                }else{
                    move(Inventory_click4);
                    Unselect_All();
                    if(i.get(3) instanceof javax.swing.JLabel){
                        javax.swing.JLabel curr = (javax.swing.JLabel) i.get(3);
                        Select(curr);
                    }
                }
            }
        }
    }//GEN-LAST:event_CrowbarMouseClicked

    private void lubang_toiletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lubang_toiletMouseClicked
        timer.stop();
        Highscore hs = new Highscore(4, username, minute*60+second);
        this.setVisible(false);
        if (clip != null) {
            clip.stop();
        }
        sl.setVisible(true);
        hs.setVisible(true);
        if (setting.isPlaying_music()) {
            main.start();
            main.loop(Clip.LOOP_CONTINUOUSLY);
        }
    }//GEN-LAST:event_lubang_toiletMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Crowbar;
    private javax.swing.JLabel Gunting;
    private javax.swing.JLabel Inventory_backgound;
    private javax.swing.JLabel Inventory_click1;
    private javax.swing.JLabel Inventory_click2;
    private javax.swing.JLabel Inventory_click3;
    private javax.swing.JLabel Inventory_click4;
    private javax.swing.JLabel Invetory_box1;
    private javax.swing.JLabel Invetory_box2;
    private javax.swing.JLabel Invetory_box3;
    private javax.swing.JLabel Invetory_box4;
    private javax.swing.JLabel Obeng;
    private javax.swing.JLabel Palinggis;
    private javax.swing.JLabel Palu;
    private javax.swing.JLabel Timer;
    private javax.swing.JLabel background;
    private javax.swing.JLabel hint_0;
    private javax.swing.JLabel hint_1;
    private javax.swing.JLabel hint_2;
    private javax.swing.JLabel hint_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel karpet;
    private javax.swing.JLabel keranjang_baju;
    private javax.swing.JLabel lampu;
    private javax.swing.JLabel lubang_toilet;
    private javax.swing.JLabel mesin_cuci;
    private javax.swing.JLabel papan_penunjuk_1;
    private javax.swing.JLabel sofa;
    private javax.swing.JLabel tali;
    private javax.swing.JLabel toilet;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Select(JLabel curr) {
        if (curr.getName().equals("gunting")) {
            gunting = true;
        }else if(curr.getName().equals("obeng")){
            obeng = true;
        }else if (curr.getName().equals("crowbar")) {
            crowbar = true;
        }else if (curr.getName().equals("palu")) {
            palu = true;
        }else if (curr.getName().equals("palinggis")) {
            palinggis = true;
        }
    }

    @Override
    public void Unselect(JLabel curr) {
        if (curr.getName().equals("gunting")) {
            gunting = false;
        }else if(curr.getName().equals("obeng")){
            obeng = false;
        }else if (curr.getName().equals("crowbar")) {
            crowbar = false;
        }else if (curr.getName().equals("palu")) {
            palu = false;
        }else if (curr.getName().equals("palinggis")) {
            palinggis = false;
        }
    }

    @Override
    public void Unselect_All() {
        gunting = false;
        obeng = false;
        crowbar = false;
        palu = false;
        palinggis = false;
    }

    @Override
    public void move(JLabel l) {
       l.setVisible(true);
        tmp.add(l);
        click = true;
    }

    @Override
    public void stay(JLabel l) {
        l.setVisible(false);
        tmp.clear();
        click = false;
    }

    @Override
    public void Hint() {
        if(!cek(Gunting)){
            JOptionPane.showMessageDialog(this, hint[0]);
        }else if(!cek(Obeng)){
            JOptionPane.showMessageDialog(this, hint[1]);
        }else if(!cek(Crowbar)){
            JOptionPane.showMessageDialog(this, hint[2]);
        }else if(!cek(Palinggis)){
            JOptionPane.showMessageDialog(this, hint[3]);
        }else if(!(toilet2)){
            JOptionPane.showMessageDialog(this, hint[4]);
        }else{
            JOptionPane.showMessageDialog(this, hint[5]);
        }
    }
    
    private void new_Set(){
        for (int j = 0; j < 4; j++) {
            if (i.get(j) != null) {
                if (i.get(j) == Gunting) {
                    Gunting.setLocation(1250, coord_y[j]);
                }else if (i.get(j) == Palu) {
                    Palu.setLocation(1250, coord_y[j]);
                }else if (i.get(j) == Obeng) {
                    Obeng.setLocation(1250, coord_y[j]);
                }else if (i.get(j) == Crowbar) {
                    Crowbar.setLocation(1250, coord_y[j]);
                }else if (i.get(j) == Palinggis) {
                    Palinggis.setLocation(1250, coord_y[j]);
                }
            }
        }
    }
}
