package pbo.projek;

import java.awt.Color;
import java.io.File;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    Akun akun = new Akun();
    
    public void Hover_on(javax.swing.JButton b){
        b.setBackground(Color.BLACK);
        b.setForeground(Color.WHITE);
    }
    
    public void Hover_off(javax.swing.JButton b){
        b.setBackground(Color.WHITE);
        b.setForeground(Color.BLACK);
    }
//=====================================================================================================================================================    
    // Music
    private Clip clip;
    public void Playmusic(String musiclocation) {
        try {
            File musicPath = new File(musiclocation);

            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                clip.loop(Clip.LOOP_CONTINUOUSLY);
            } else {
                System.out.println("Can't find file");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
//=====================================================================================================================================================
    private Setting setting;
    
    /**
     * Creates new form Main
     */
    
    public Main() {
        initComponents();
        Playmusic("Music\\Main.wav");
        setting = new Setting(clip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Account = new javax.swing.JFrame();
        save = new javax.swing.JButton();
        Hapus_akun = new javax.swing.JButton();
        ask1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        ask2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Reset = new javax.swing.JFrame();
        Reset_data_game = new javax.swing.JButton();
        Reset_data_akun = new javax.swing.JButton();
        Hello = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        BPlay = new javax.swing.JButton();
        BSetting = new javax.swing.JButton();
        BReset = new javax.swing.JLabel();
        LBackground = new javax.swing.JLabel();

        Account.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Account.setTitle("Akun");
        Account.setLocation(new java.awt.Point(450, 350));
        Account.setMinimumSize(new java.awt.Dimension(453, 228));
        Account.setResizable(false);

        save.setText("SAVE");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.setPreferredSize(new java.awt.Dimension(60, 25));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        Hapus_akun.setText("Hapus Akun");
        Hapus_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hapus_akunMouseClicked(evt);
            }
        });

        ask1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ask1.setText("Username :");

        Username.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        ask2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ask2.setText("Password  : ");

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("* Jika username yang dimasukkan belum ada maka akan otomatis terdaftar");

        Password.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout AccountLayout = new javax.swing.GroupLayout(Account.getContentPane());
        Account.getContentPane().setLayout(AccountLayout);
        AccountLayout.setHorizontalGroup(
            AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountLayout.createSequentialGroup()
                .addGroup(AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AccountLayout.createSequentialGroup()
                                .addGroup(AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ask1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ask2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password)
                                    .addComponent(Username)))
                            .addComponent(jLabel2)
                            .addGroup(AccountLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(Hapus_akun))))
                    .addGroup(AccountLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        AccountLayout.setVerticalGroup(
            AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ask1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ask2)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus_akun))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        Reset.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Reset.setTitle("Reset");
        Reset.setLocation(new java.awt.Point(1100, 550));
        Reset.setMinimumSize(new java.awt.Dimension(285, 94));
        Reset.setResizable(false);

        Reset_data_game.setText("Reset Data");
        Reset_data_game.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reset_data_gameMouseClicked(evt);
            }
        });

        Reset_data_akun.setText("Reset Data Akun");
        Reset_data_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reset_data_akunMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ResetLayout = new javax.swing.GroupLayout(Reset.getContentPane());
        Reset.getContentPane().setLayout(ResetLayout);
        ResetLayout.setHorizontalGroup(
            ResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResetLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Reset_data_game)
                .addGap(15, 15, 15)
                .addComponent(Reset_data_akun)
                .addGap(25, 25, 25))
        );
        ResetLayout.setVerticalGroup(
            ResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResetLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset_data_game)
                    .addComponent(Reset_data_akun))
                .addGap(15, 15, 15))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escape Room");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1404, 787));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 789));
        getContentPane().setLayout(null);

        Hello.setFont(new java.awt.Font("Chiller", 3, 36)); // NOI18N
        Hello.setForeground(new java.awt.Color(255, 255, 255));
        Hello.setText("HELLO,");
        getContentPane().add(Hello);
        Hello.setBounds(40, 60, 100, 40);

        Name.setFont(new java.awt.Font("Chiller", 3, 40)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Guest");
        Name.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameMouseClicked(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(150, 60, 340, 40);

        BPlay.setBackground(new java.awt.Color(255, 255, 255));
        BPlay.setFont(new java.awt.Font("Ravie", 0, 38)); // NOI18N
        BPlay.setText("Play");
        BPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BPlay.setPreferredSize(new java.awt.Dimension(400, 100));
        BPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BPlayMouseExited(evt);
            }
        });
        getContentPane().add(BPlay);
        BPlay.setBounds(500, 400, 400, 100);

        BSetting.setBackground(new java.awt.Color(255, 255, 255));
        BSetting.setFont(new java.awt.Font("Ravie", 0, 38)); // NOI18N
        BSetting.setText("Setting");
        BSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BSetting.setMaximumSize(new java.awt.Dimension(55, 25));
        BSetting.setMinimumSize(new java.awt.Dimension(55, 25));
        BSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BSettingMouseExited(evt);
            }
        });
        getContentPane().add(BSetting);
        BSetting.setBounds(500, 550, 400, 100);

        BReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/reset.png"))); // NOI18N
        BReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BResetMouseClicked(evt);
            }
        });
        getContentPane().add(BReset);
        BReset.setBounds(1275, 625, 100, 100);

        LBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Main_Background.png"))); // NOI18N
        getContentPane().add(LBackground);
        LBackground.setBounds(0, 0, 1400, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPlayMouseExited
        Hover_off(BPlay);
    }//GEN-LAST:event_BPlayMouseExited

    private void BSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSettingMouseEntered
        Hover_on(BSetting);
    }//GEN-LAST:event_BSettingMouseEntered

    private void BSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSettingMouseExited
        Hover_off(BSetting);
    }//GEN-LAST:event_BSettingMouseExited

    private void BPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPlayMouseEntered
        Hover_on(BPlay);
    }//GEN-LAST:event_BPlayMouseEntered

    private void BPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPlayMouseClicked
        if(akun.getCurrUser() != null){
            this.setVisible(false);
            new Select_Level(akun.getCurrUser(), clip, this, setting).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Masukkan nama terlebih dahulu!", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BPlayMouseClicked

    private void NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameMouseClicked
        Username.setText("");
        Password.setText("");
        Account.setVisible(true);
    }//GEN-LAST:event_NameMouseClicked
    
    private void BSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSettingMouseClicked
        setting.setVisible(true);
    }//GEN-LAST:event_BSettingMouseClicked

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // Account
    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        String username = Username.getText();
        String password = Password.getText();
        String hashtext;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(password.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
        }
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
        
        boolean islogin = false;
        if(akun.cek_user_ada(username)){
            akun.regis(username, hashtext);
            akun.loaduser();
            if(akun.isAccount_Exist(username, hashtext)){
                islogin = true;
            }
        }else{
            if(akun.isAccount_Exist(username, hashtext)){
                islogin = true;
            }else{
                JOptionPane.showMessageDialog(this, "Login Gagal!", "Failed", JOptionPane.ERROR_MESSAGE); //gagal
            }
        }
        
        if (islogin) {
            akun = new Akun(username);
            JOptionPane.showMessageDialog(this, "Berhasil Login", "Success", JOptionPane.INFORMATION_MESSAGE); //sukses
            Name.setText(username);
            Account.setVisible(false);
            islogin = false;
        }
    }//GEN-LAST:event_saveMouseClicked

    private void Hapus_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hapus_akunMouseClicked
        String username = Username.getText();
        String password = Password.getText();
        String hashtext;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(password.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
        }
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
        
        if(akun.isAccount_Exist(username, hashtext)){
            akun.reset(username, "#");
            if (Name.getText().equals(username)) {
                Name.setText("Guest");
                akun = new Akun();
            }else{
                akun.loaduser();
            }
            JOptionPane.showMessageDialog(this, "Berhasil menghapus akun " + username, "Success", JOptionPane.INFORMATION_MESSAGE); //sukses
            Username.setText("");
            Password.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Username atau Password salah!", "Failed", JOptionPane.ERROR_MESSAGE); //gagal
        }
    }//GEN-LAST:event_Hapus_akunMouseClicked
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // Reset
    private void BResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BResetMouseClicked
        Reset.setVisible(true);
    }//GEN-LAST:event_BResetMouseClicked

    private void Reset_data_gameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset_data_gameMouseClicked
        akun.reset("", "$3mu4");
        akun = new Akun();
        Name.setText("Guest");
        Reset.setVisible(false);
        JOptionPane.showMessageDialog(this, "Reset game berhasil", "Success", JOptionPane.INFORMATION_MESSAGE); //sukses
    }//GEN-LAST:event_Reset_data_gameMouseClicked

    private void Reset_data_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset_data_akunMouseClicked
        if (akun.getCurrUser() == null) {
            Reset.setVisible(false);
            JOptionPane.showMessageDialog(this, "Tidak login ke akun manapun!", "Failed", JOptionPane.ERROR_MESSAGE); //gagal
        }else{
            akun.reset(Name.getText(), "4kuN");
            akun.loaduser();
            Reset.setVisible(false);
            JOptionPane.showMessageDialog(this, "Reset Akun " + Name.getText() + " berhasil", "Success", JOptionPane.INFORMATION_MESSAGE); //sukses
        }
    }//GEN-LAST:event_Reset_data_akunMouseClicked
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Account;
    private javax.swing.JButton BPlay;
    private javax.swing.JLabel BReset;
    private javax.swing.JButton BSetting;
    private javax.swing.JButton Hapus_akun;
    private javax.swing.JLabel Hello;
    private javax.swing.JLabel LBackground;
    private javax.swing.JLabel Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JFrame Reset;
    private javax.swing.JButton Reset_data_akun;
    private javax.swing.JButton Reset_data_game;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel ask1;
    private javax.swing.JLabel ask2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
