package pbo.projek;

import pbo.Level1.Level1;
import pbo.Level2.Level2;
import pbo.Level3.Level3;
import pbo.Level4.Level4;

import javax.sound.sampled.Clip;

public class Select_Level extends javax.swing.JFrame {
    
    public void Hover(javax.swing.JLabel t, javax.swing.JLabel f){
        f.setVisible(false);
        t.setVisible(true);
    }
    
    private Clip clip;
    private Main main;
    private Setting setting;
    private String currUser;

    /**
     * Creates new form Select_Level
     */
    public Select_Level() {
        initComponents();
    }
    
    public Select_Level(String currUser, Clip clip, Main main, Setting setting) {
        initComponents();
        this.clip = clip;
        this.main = main;
        this.setting = setting;
        this.currUser = currUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Door_Level1 = new javax.swing.JLabel();
        Door_Level1_h = new javax.swing.JLabel();
        Door_Level1_h.setVisible(false);
        Door_Level2 = new javax.swing.JLabel();
        Door_Level2_h = new javax.swing.JLabel();
        Door_Level1_h.setVisible(false);
        Door_Level3 = new javax.swing.JLabel();
        Door_Level3_h = new javax.swing.JLabel();
        Door_Level1_h.setVisible(false);
        Door_Level4 = new javax.swing.JLabel();
        Door_Level4_h = new javax.swing.JLabel();
        Door_Level1_h.setVisible(false);
        Papan_Level1 = new javax.swing.JLabel();
        Papan_Level2 = new javax.swing.JLabel();
        Papan_Level3 = new javax.swing.JLabel();
        Papan_Level4 = new javax.swing.JLabel();
        LLantai = new javax.swing.JLabel();
        LJudul = new javax.swing.JLabel();
        Icon_Back = new javax.swing.JLabel();
        Icon_Setting = new javax.swing.JLabel();
        LRetakan1 = new javax.swing.JLabel();
        LRetakan2 = new javax.swing.JLabel();
        LBackgound_Tembok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Select Level");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1400, 789));
        setMinimumSize(new java.awt.Dimension(1400, 789));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 789));
        getContentPane().setLayout(null);

        Door_Level1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Level_DoorClose.png"))); // NOI18N
        Door_Level1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Door_Level1MouseEntered(evt);
            }
        });
        getContentPane().add(Door_Level1);
        Door_Level1.setBounds(140, 360, 175, 300);

        Door_Level1_h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Level_DoorOpen.png"))); // NOI18N
        Door_Level1_h.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Door_Level1_h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Door_Level1_hMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Door_Level1_hMouseExited(evt);
            }
        });
        getContentPane().add(Door_Level1_h);
        Door_Level1_h.setBounds(140, 350, 175, 305);

        Door_Level2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Level_DoorClose.png"))); // NOI18N
        Door_Level2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Door_Level2MouseEntered(evt);
            }
        });
        getContentPane().add(Door_Level2);
        Door_Level2.setBounds(445, 360, 175, 300);

        Door_Level2_h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Level_DoorOpen.png"))); // NOI18N
        Door_Level2_h.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Door_Level2_h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Door_Level2_hMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Door_Level2_hMouseExited(evt);
            }
        });
        getContentPane().add(Door_Level2_h);
        Door_Level2_h.setBounds(445, 350, 175, 305);

        Door_Level3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Level_DoorClose.png"))); // NOI18N
        Door_Level3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Door_Level3MouseEntered(evt);
            }
        });
        getContentPane().add(Door_Level3);
        Door_Level3.setBounds(770, 360, 175, 300);

        Door_Level3_h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Level_DoorOpen.png"))); // NOI18N
        Door_Level3_h.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Door_Level3_h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Door_Level3_hMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Door_Level3_hMouseExited(evt);
            }
        });
        getContentPane().add(Door_Level3_h);
        Door_Level3_h.setBounds(770, 350, 175, 305);

        Door_Level4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Level_DoorClose.png"))); // NOI18N
        Door_Level4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Door_Level4MouseEntered(evt);
            }
        });
        getContentPane().add(Door_Level4);
        Door_Level4.setBounds(1085, 360, 175, 300);

        Door_Level4_h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Level_DoorOpen.png"))); // NOI18N
        Door_Level4_h.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Door_Level4_h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Door_Level4_hMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Door_Level4_hMouseExited(evt);
            }
        });
        getContentPane().add(Door_Level4_h);
        Door_Level4_h.setBounds(1085, 350, 175, 305);

        Papan_Level1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Papan Level (1).png"))); // NOI18N
        getContentPane().add(Papan_Level1);
        Papan_Level1.setBounds(140, 300, 175, 50);

        Papan_Level2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Papan Level (2).png"))); // NOI18N
        getContentPane().add(Papan_Level2);
        Papan_Level2.setBounds(445, 300, 175, 50);

        Papan_Level3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Papan Level (3).png"))); // NOI18N
        getContentPane().add(Papan_Level3);
        Papan_Level3.setBounds(770, 300, 175, 50);

        Papan_Level4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Papan LeveL (4).png"))); // NOI18N
        getContentPane().add(Papan_Level4);
        Papan_Level4.setBounds(1080, 300, 175, 50);

        LLantai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/lantai.png"))); // NOI18N
        getContentPane().add(LLantai);
        LLantai.setBounds(0, 390, 1410, 460);

        LJudul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/Papan Judul.png"))); // NOI18N
        getContentPane().add(LJudul);
        LJudul.setBounds(300, 40, 790, 179);

        Icon_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/back.png"))); // NOI18N
        Icon_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icon_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icon_BackMouseClicked(evt);
            }
        });
        getContentPane().add(Icon_Back);
        Icon_Back.setBounds(30, 20, 150, 100);

        Icon_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/icon_setting.png"))); // NOI18N
        Icon_Setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Icon_Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icon_SettingMouseClicked(evt);
            }
        });
        getContentPane().add(Icon_Setting);
        Icon_Setting.setBounds(1270, 20, 100, 100);

        LRetakan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/retakan.png"))); // NOI18N
        getContentPane().add(LRetakan1);
        LRetakan1.setBounds(80, 130, 490, 660);

        LRetakan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/retakan2.png"))); // NOI18N
        getContentPane().add(LRetakan2);
        LRetakan2.setBounds(700, -110, 533, 830);

        LBackgound_Tembok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/projek/Image/SelectLevel_Background.png"))); // NOI18N
        getContentPane().add(LBackgound_Tembok);
        LBackgound_Tembok.setBounds(0, 0, 1400, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Door_Level1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level1MouseEntered
        Hover(Door_Level1_h, Door_Level1);
    }//GEN-LAST:event_Door_Level1MouseEntered

    private void Door_Level1_hMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level1_hMouseExited
        Hover(Door_Level1, Door_Level1_h);
    }//GEN-LAST:event_Door_Level1_hMouseExited

    private void Door_Level1_hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level1_hMouseClicked
        this.setVisible(false);
        new Level1(currUser, this, clip, setting).setVisible(true);
        if (setting.isPlaying_music()) {
            clip.stop();
        }
    }//GEN-LAST:event_Door_Level1_hMouseClicked

    private void Door_Level2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level2MouseEntered
        Hover(Door_Level2_h, Door_Level2);
    }//GEN-LAST:event_Door_Level2MouseEntered

    private void Door_Level2_hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level2_hMouseClicked
        this.setVisible(false);
        new Level2(currUser, this, clip, setting).setVisible(true);
        if (setting.isPlaying_music()) {
            clip.stop();
        }
    }//GEN-LAST:event_Door_Level2_hMouseClicked

    private void Door_Level2_hMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level2_hMouseExited
        Hover(Door_Level2, Door_Level2_h);
    }//GEN-LAST:event_Door_Level2_hMouseExited

    private void Door_Level3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level3MouseEntered
        Hover(Door_Level3_h, Door_Level3);
    }//GEN-LAST:event_Door_Level3MouseEntered

    private void Door_Level3_hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level3_hMouseClicked
        this.setVisible(false);
        new Level3(currUser, this, clip, setting).setVisible(true);
        if (setting.isPlaying_music()) {
            clip.stop();
        }
    }//GEN-LAST:event_Door_Level3_hMouseClicked

    private void Door_Level3_hMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level3_hMouseExited
        Hover(Door_Level3, Door_Level3_h);
    }//GEN-LAST:event_Door_Level3_hMouseExited

    private void Door_Level4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level4MouseEntered
        Hover(Door_Level4_h, Door_Level4);
    }//GEN-LAST:event_Door_Level4MouseEntered

    private void Door_Level4_hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level4_hMouseClicked
        this.setVisible(false);
        new Level4(currUser, this, clip, setting).setVisible(true);
        if (setting.isPlaying_music()) {
            clip.stop();
        }
    }//GEN-LAST:event_Door_Level4_hMouseClicked

    private void Door_Level4_hMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Door_Level4_hMouseExited
        Hover(Door_Level4, Door_Level4_h);
    }//GEN-LAST:event_Door_Level4_hMouseExited

    private void Icon_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icon_BackMouseClicked
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_Icon_BackMouseClicked

    private void Icon_SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icon_SettingMouseClicked
        setting.setVisible(true);
    }//GEN-LAST:event_Icon_SettingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select_Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select_Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select_Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select_Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select_Level().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Door_Level1;
    private javax.swing.JLabel Door_Level1_h;
    private javax.swing.JLabel Door_Level2;
    private javax.swing.JLabel Door_Level2_h;
    private javax.swing.JLabel Door_Level3;
    private javax.swing.JLabel Door_Level3_h;
    private javax.swing.JLabel Door_Level4;
    private javax.swing.JLabel Door_Level4_h;
    private javax.swing.JLabel Icon_Back;
    private javax.swing.JLabel Icon_Setting;
    private javax.swing.JLabel LBackgound_Tembok;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LLantai;
    private javax.swing.JLabel LRetakan1;
    private javax.swing.JLabel LRetakan2;
    private javax.swing.JLabel Papan_Level1;
    private javax.swing.JLabel Papan_Level2;
    private javax.swing.JLabel Papan_Level3;
    private javax.swing.JLabel Papan_Level4;
    // End of variables declaration//GEN-END:variables
}
