package pbo.projek;

import java.awt.Color;
import javax.sound.sampled.Clip;
import javax.swing.Timer;

public class Setting extends javax.swing.JFrame {

    private Clip music;
    private boolean Playing_music = true;
    
    public void Hover( javax.swing.JLabel lvl, boolean in_out){
        if (in_out) {
            lvl.setForeground(Color.blue);
        }else{
            lvl.setForeground(Color.black);
        }
    }
    
    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
    }
    
    public Setting(Clip clip) {
        initComponents();
        this.music = clip;
    }

    public boolean isPlaying_music(){
        return Playing_music;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        On = new javax.swing.JRadioButton();
        Off = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Highscore1 = new javax.swing.JLabel();
        Lvl1 = new javax.swing.JLabel();
        Lvl2 = new javax.swing.JLabel();
        Lvl3 = new javax.swing.JLabel();
        Lvl4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setting");
        setLocation(new java.awt.Point(585, 400));
        setResizable(false);

        buttonGroup1.add(On);
        On.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        On.setSelected(true);
        On.setText("ON");
        On.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnActionPerformed(evt);
            }
        });

        buttonGroup1.add(Off);
        Off.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Off.setText("OFF");
        Off.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Music :");

        Highscore1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Highscore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Highscore1.setText("HighScore :");

        Lvl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lvl1.setText("Level 1");
        Lvl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lvl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lvl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lvl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lvl1MouseExited(evt);
            }
        });

        Lvl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lvl2.setText("Level 2");
        Lvl2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lvl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lvl2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lvl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lvl2MouseExited(evt);
            }
        });

        Lvl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lvl3.setText("Level 3");
        Lvl3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lvl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lvl3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lvl3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lvl3MouseExited(evt);
            }
        });

        Lvl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lvl4.setText("Level 4");
        Lvl4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lvl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lvl4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lvl4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lvl4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15)
                                .addComponent(On))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Lvl3)
                                    .addGap(25, 25, 25)
                                    .addComponent(Lvl4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Lvl1)
                                    .addGap(25, 25, 25)
                                    .addComponent(Lvl2))))
                        .addGap(10, 10, 10)
                        .addComponent(Off))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(Highscore1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(On)
                    .addComponent(Off))
                .addGap(10, 10, 10)
                .addComponent(Highscore1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lvl1)
                    .addComponent(Lvl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lvl4)
                    .addComponent(Lvl3))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnActionPerformed
        music.start();
        music.loop(Clip.LOOP_CONTINUOUSLY);
        Playing_music = true;
    }//GEN-LAST:event_OnActionPerformed

    private void OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffActionPerformed
        music.stop();
        Playing_music = false;
    }//GEN-LAST:event_OffActionPerformed

    private void Lvl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl1MouseEntered
        Hover(Lvl1, true);
    }//GEN-LAST:event_Lvl1MouseEntered

    private void Lvl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl1MouseExited
        Hover(Lvl1, false);
    }//GEN-LAST:event_Lvl1MouseExited

    private void Lvl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl2MouseEntered
        Hover(Lvl2, true);
    }//GEN-LAST:event_Lvl2MouseEntered

    private void Lvl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl2MouseExited
        Hover(Lvl2, false);
    }//GEN-LAST:event_Lvl2MouseExited

    private void Lvl3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl3MouseEntered
        Hover(Lvl3, true);
    }//GEN-LAST:event_Lvl3MouseEntered

    private void Lvl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl3MouseExited
        Hover(Lvl3, false);
    }//GEN-LAST:event_Lvl3MouseExited

    private void Lvl4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl4MouseEntered
        Hover(Lvl4, true);
    }//GEN-LAST:event_Lvl4MouseEntered

    private void Lvl4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl4MouseExited
        Hover(Lvl4, false);
    }//GEN-LAST:event_Lvl4MouseExited

    private void Lvl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl1MouseClicked
        Highscore hs = new Highscore(1,"4d-M1n",0);
        hs.setVisible(true);
    }//GEN-LAST:event_Lvl1MouseClicked

    private void Lvl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl2MouseClicked
        Highscore hs = new Highscore(2,"4d-M1n",0);
        hs.setVisible(true);
    }//GEN-LAST:event_Lvl2MouseClicked

    private void Lvl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl3MouseClicked
        Highscore hs = new Highscore(3,"4d-M1n",0);
        hs.setVisible(true);
    }//GEN-LAST:event_Lvl3MouseClicked

    private void Lvl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lvl4MouseClicked
        Highscore hs = new Highscore(4,"4d-M1n",0);
        hs.setVisible(true);
    }//GEN-LAST:event_Lvl4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Highscore1;
    private javax.swing.JLabel Lvl1;
    private javax.swing.JLabel Lvl2;
    private javax.swing.JLabel Lvl3;
    private javax.swing.JLabel Lvl4;
    private javax.swing.JRadioButton Off;
    private javax.swing.JRadioButton On;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
